import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.185.1/build/three.module.min.js';
import { VEHICLES, TRACKS, BALANCE } from './game-data.js';

const $ = (q, r=document) => r.querySelector(q);
const $$ = (q, r=document) => [...r.querySelectorAll(q)];
const clamp = (v,a,b)=>Math.max(a,Math.min(b,v));
const lerp = (a,b,t)=>a+(b-a)*t;
const smoothstep = t => { t=clamp(t,0,1); return t*t*(3-2*t); };
const TAU = Math.PI*2;
const rad = d=>d*Math.PI/180;
const fmtTime = s => { const m=Math.floor(s/60), ss=Math.floor(s%60), cs=Math.floor((s%1)*100); return `${String(m).padStart(2,'0')}:${String(ss).padStart(2,'0')}.${String(cs).padStart(2,'0')}`; };
const hex = s => new THREE.Color(s || '#ffffff');
const copy = o => JSON.parse(JSON.stringify(o));
const dist2 = (a,b)=>Math.hypot(a.x-b.x,a.z-b.z);
const wrapIndex = (i,n)=>(i%n+n)%n;

function cardinalPoint(p0,p1,p2,p3,t,tension=.58){
  const s=clamp(1-tension,0,1)*.5;
  const m1={x:(p2.x-p0.x)*s,y:(p2.y-p0.y)*s,z:(p2.z-p0.z)*s};
  const m2={x:(p3.x-p1.x)*s,y:(p3.y-p1.y)*s,z:(p3.z-p1.z)*s};
  const t2=t*t,t3=t2*t,h00=2*t3-3*t2+1,h10=t3-2*t2+t,h01=-2*t3+3*t2,h11=t3-t2;
  return {x:h00*p1.x+h10*m1.x+h01*p2.x+h11*m2.x,y:h00*p1.y+h10*m1.y+h01*p2.y+h11*m2.y,z:h00*p1.z+h10*m1.z+h01*p2.z+h11*m2.z};
}
function sampleClosedRoute(points,samples=5,tension=.58){
  const c=points.map(p=>({x:+p[0],y:+p[1],z:+p[2]})), out=[], src=[]; const n=c.length;
  for(let i=0;i<n;i++) for(let s=0;s<samples;s++){ out.push(cardinalPoint(c[wrapIndex(i-1,n)],c[i],c[(i+1)%n],c[(i+2)%n],s/samples,tension)); src.push(i); }
  return {points:out,source:src,samples};
}
function sampleOpenRoute(points,samples=4,tension=.65){
  const c=points.map(p=>({x:+p[0],y:+p[1],z:+p[2]})); if(c.length<2) return {points:[],source:[]}; const out=[],src=[];
  if(c.length===2){for(let i=0;i<=samples;i++){const t=i/samples;out.push({x:lerp(c[0].x,c[1].x,t),y:lerp(c[0].y,c[1].y,t),z:lerp(c[0].z,c[1].z,t)});src.push(0)} return {points:out,source:src};}
  for(let i=0;i<c.length-1;i++){const p0=i?c[i-1]:c[i],p1=c[i],p2=c[i+1],p3=i+2<c.length?c[i+2]:c[i+1];for(let s=0;s<samples;s++){out.push(cardinalPoint(p0,p1,p2,p3,s/samples,tension));src.push(i)}} out.push(c.at(-1));src.push(c.length-2);return {points:out,source:src};
}
function interpolateVehicle(a,b,t){
  const av=a.advanced||{},bv=b.advanced||{};
  const ar=av.ram||{},br=bv.ram||{}, at=av.time_control||{},bt=bv.time_control||{}, an=av.nitro||{},bn=bv.nitro||{};
  const f=(k)=>lerp(+a[k],+b[k],t), g=(x,y,k,d)=>lerp(+(x[k]??d),+(y[k]??d),t);
  return {
    top_speed:f('top_speed'),acceleration:f('acceleration'),robustness:f('robustness'),resistance:f('resistance'),control:f('control'),mass:f('mass'),grip:f('grip'),braking:f('braking'),push_force:f('push_force'),max_health:f('max_health'),
    ram_max_time:g(ar,br,'max_time',5),ram_acceleration_multiplier:g(ar,br,'acceleration_multiplier',1.25),ram_top_speed_multiplier:g(ar,br,'top_speed_multiplier',1.12),ram_damage_multiplier:g(ar,br,'damage_multiplier',1.75),
    time_control_max:g(at,bt,'max_time',3),time_control_control_multiplier:g(at,bt,'control_multiplier',1.45),nitro_capacity:g(an,bn,'capacity',100),
    nitro_base_speed_multiplier:g(an.base||{},bn.base||{},'top_speed_multiplier',1.07),nitro_base_acceleration_multiplier:g(an.base||{},bn.base||{},'acceleration_multiplier',1.14),
    nitro_remix_speed_multiplier:g(an.remix||{},bn.remix||{},'top_speed_multiplier',1.16),nitro_remix_acceleration_multiplier:g(an.remix||{},bn.remix||{},'acceleration_multiplier',1.28),
    nitro_turbo_speed_multiplier:g(an.turbo||{},bn.turbo||{},'top_speed_multiplier',1.3),nitro_turbo_acceleration_multiplier:g(an.turbo||{},bn.turbo||{},'acceleration_multiplier',1.52)
  };
}

class AudioSynth{
  constructor(){this.ctx=null;this.master=.12;this.beat=0}
  wake(){if(!this.ctx){this.ctx=new (window.AudioContext||window.webkitAudioContext)()} if(this.ctx.state==='suspended') this.ctx.resume()}
  tone(freq=440,dur=.07,type='sine',gain=.08){if(!this.ctx)return;const o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(gain*this.master,this.ctx.currentTime);g.gain.exponentialRampToValueAtTime(.0001,this.ctx.currentTime+dur);o.connect(g);g.connect(this.ctx.destination);o.start();o.stop(this.ctx.currentTime+dur)}
  update(dt,intense=false){if(!this.ctx)return;this.beat-=dt;if(this.beat<=0){this.beat=intense?.18:.42;this.tone(intense?110:80,.05,'square',intense?.07:.035)}}
}
const audio=new AudioSynth();

class ThreeWorld{
  constructor(canvas){
    this.canvas=canvas; this.renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));this.renderer.shadowMap.enabled=false;this.renderer.outputColorSpace=THREE.SRGBColorSpace;
    this.scene=new THREE.Scene();this.scene.background=new THREE.Color('#09131d');this.scene.fog=new THREE.Fog('#09131d',65,360);
    this.camera=new THREE.PerspectiveCamera(66,innerWidth/innerHeight,.1,900);this.camera.position.set(0,8,-16);
    this.scene.add(new THREE.HemisphereLight('#9bd5ff','#18220f',2.3));const sun=new THREE.DirectionalLight('#fff2d0',2.5);sun.position.set(-80,120,-30);this.scene.add(sun);
    this.root=new THREE.Group();this.scene.add(this.root);this.roadRoot=new THREE.Group();this.carRoot=new THREE.Group();this.root.add(this.roadRoot,this.carRoot);
    this.clock=0;this.mode='menu';this.playerMesh=null;this.botMeshes=[];this.trackRuntime=null;this.resize();window.addEventListener('resize',()=>this.resize());
    this.showMenuScene();
  }
  resize(){const w=innerWidth,h=innerHeight;this.renderer.setSize(w,h,false);this.camera.aspect=w/h;this.camera.updateProjectionMatrix()}
  clear(group){while(group.children.length){const o=group.children.pop();o.traverse?.(n=>{n.geometry?.dispose?.();if(n.material){(Array.isArray(n.material)?n.material:[n.material]).forEach(m=>m.dispose?.())}})}}
  showMenuScene(){this.mode='menu';this.clear(this.roadRoot);this.clear(this.carRoot);this.scene.background=new THREE.Color('#07111a');this.scene.fog.color.set('#07111a');
    const floor=new THREE.Mesh(new THREE.PlaneGeometry(220,220),new THREE.MeshStandardMaterial({color:'#0f1b24',roughness:.8,metalness:.15}));floor.rotation.x=-Math.PI/2;this.roadRoot.add(floor);
    for(let i=0;i<16;i++){const b=new THREE.Mesh(new THREE.BoxGeometry(8+Math.random()*10,12+Math.random()*45,8+Math.random()*10),new THREE.MeshStandardMaterial({color:i%3===0?'#15314a':'#102330',roughness:.9}));const a=i/16*TAU,r=45+Math.random()*45;b.position.set(Math.cos(a)*r,b.geometry.parameters.height/2,Math.sin(a)*r);this.roadRoot.add(b)}
    const car=this.makeCar(VEHICLES[1]);car.position.set(0,.5,0);this.carRoot.add(car);this.playerMesh=car;this.camera.position.set(9,5,-12);this.camera.lookAt(0,1,0);
  }
  makeCar(v,colorOverride=null){const g=new THREE.Group();const mat=new THREE.MeshStandardMaterial({color:colorOverride||v.color,roughness:.38,metalness:.38});const dark=new THREE.MeshStandardMaterial({color:'#081018',roughness:.22,metalness:.5});const body=new THREE.Mesh(new THREE.BoxGeometry(1,1,1),mat);body.name='body';body.scale.set(v.visual_scale[0],Math.max(.32,v.visual_scale[1]),v.visual_scale[2]);body.position.y=.42;g.add(body);const cab=new THREE.Mesh(new THREE.BoxGeometry(1,1,1),new THREE.MeshStandardMaterial({color:'#17354b',roughness:.18,metalness:.35}));cab.name='cabin';cab.scale.set(v.visual_scale[0]*.72,v.visual_scale[1]*.8,v.visual_scale[2]*.43);cab.position.set(0,.8,-v.visual_scale[2]*.06);g.add(cab);
    const wheelGeo=new THREE.CylinderGeometry(.28,.28,.22,12);for(const sx of [-1,1])for(const sz of [-1,1]){const w=new THREE.Mesh(wheelGeo,dark);w.rotation.z=Math.PI/2;w.position.set(sx*v.visual_scale[0]*.55,.25,sz*v.visual_scale[2]*.31);g.add(w)}g.userData.vehicle=v;return g}
  updateCarMorph(mesh,a,b,t){if(!mesh)return;const body=mesh.getObjectByName('body'),cab=mesh.getObjectByName('cabin');const sx=lerp(a.visual_scale[0],b.visual_scale[0],t),sy=lerp(a.visual_scale[1],b.visual_scale[1],t),sz=lerp(a.visual_scale[2],b.visual_scale[2],t);body.scale.set(sx,Math.max(.32,sy),sz);cab.scale.set(sx*.72,sy*.8,sz*.43);const ca=hex(a.color),cb=hex(b.color);body.material.color.copy(ca.lerp(cb,t))}
  showGarage(a,b){this.mode='garage';this.clear(this.roadRoot);this.clear(this.carRoot);this.scene.background=new THREE.Color('#07111a');const floor=new THREE.Mesh(new THREE.PlaneGeometry(100,100),new THREE.MeshStandardMaterial({color:'#122231',roughness:.78}));floor.rotation.x=-Math.PI/2;this.roadRoot.add(floor);const plat=new THREE.Mesh(new THREE.CylinderGeometry(5.3,5.5,.55,48),new THREE.MeshStandardMaterial({color:'#152a39',metalness:.6,roughness:.3}));plat.position.y=.28;this.roadRoot.add(plat);const ring=new THREE.Mesh(new THREE.TorusGeometry(4.65,.08,12,72),new THREE.MeshBasicMaterial({color:'#13aef5'}));ring.rotation.x=Math.PI/2;ring.position.y=.6;this.roadRoot.add(ring);this.playerMesh=this.makeCar(a);this.playerMesh.position.y=.75;this.carRoot.add(this.playerMesh);this._garageA=a;this._garageB=b;this.camera.position.set(-8,4.1,-8);this.camera.lookAt(0,1.1,0)}
  profileWidth(track,source){let w=+track.width||14;for(const p of track.road_profiles||[]){let f=+p.from,t=+p.to;if(f<=t&&source>=f&&source<=t)w=+p.width||w;else if(f>t&&(source>=f||source<=t))w=+p.width||w}return w}
  surfaceFor(track,source){let grip=1,color='#35383d';for(const s of track.surfaces||[]){const f=+s.from,t=+s.to;if((f<=t&&source>=f&&source<=t)||(f>t&&(source>=f||source<=t))){grip=+s.grip||1;color=s.color||color}}return{grip,color}}
  buildTrack(track){this.mode='race';this.clear(this.roadRoot);this.clear(this.carRoot);const env=track.environment||{};this.scene.background=new THREE.Color(env.sky_color||env.sky||'#7b9bad');this.scene.fog.color.copy(this.scene.background);this.scene.fog.near=+env.fog_near||110;this.scene.fog.far=+env.fog_far||430;
    const sm=track.route_smoothing||{},sampled=sampleClosedRoute(track.waypoints,sm.samples_per_segment||5,sm.tension||.58),pts=sampled.points,n=pts.length;
    const pos=[],colors=[],idx=[];for(let i=0;i<n;i++){const p=pts[i],prev=pts[wrapIndex(i-1,n)],next=pts[(i+1)%n],dx=next.x-prev.x,dz=next.z-prev.z,len=Math.hypot(dx,dz)||1,nx=-dz/len,nz=dx/len,w=this.profileWidth(track,sampled.source[i]);const surface=this.surfaceFor(track,sampled.source[i]),c=hex(surface.color);pos.push(p.x+nx*w/2,p.y+.02,p.z+nz*w/2,p.x-nx*w/2,p.y+.02,p.z-nz*w/2);for(let q=0;q<2;q++)colors.push(c.r,c.g,c.b);}
    for(let i=0;i<n;i++){const j=(i+1)%n,li=i*2,ri=li+1,lj=j*2,rj=lj+1;idx.push(li,ri,lj,ri,rj,lj)}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));geo.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));geo.setIndex(idx);geo.computeVertexNormals();const road=new THREE.Mesh(geo,new THREE.MeshStandardMaterial({vertexColors:true,roughness:.92,metalness:.02,side:THREE.DoubleSide}));this.roadRoot.add(road);
    const centerGeo=new THREE.BufferGeometry().setFromPoints(pts.map(p=>new THREE.Vector3(p.x,p.y+.06,p.z)));this.roadRoot.add(new THREE.LineLoop(centerGeo,new THREE.LineBasicMaterial({color:'#dce4e8',transparent:true,opacity:.5})));
    const ground=new THREE.Mesh(new THREE.PlaneGeometry(1100,1100),new THREE.MeshStandardMaterial({color:env.terrain_color||env.ground||'#335746',roughness:1}));ground.rotation.x=-Math.PI/2;ground.position.y=-.08;this.roadRoot.add(ground);
    for(const sc of track.scenery_zones||[]) this.addSceneryZone(sc);
    for(const ramp of track.ramps||[]) this.addRamp(ramp);
    const tunnels=new Set((track.tunnel_segments||[]).map(Number));for(let i=0;i<n;i+=2)if(tunnels.has(sampled.source[i]))this.addTunnelFrame(pts,i,track,sampled.source[i]);
    const shortcutRuns=[];for(const r of track.alternate_roads||[]){const sr=sampleOpenRoute(r.points,r.samples_per_segment||4,r.tension||.65);shortcutRuns.push(sr.points);this.addOpenRoad(sr.points,+r.width||(+track.width||14)*.72,r.color||'#42464a')}
    this.trackRuntime={track,points:pts,source:sampled.source,samples:sampled.samples,shortcutRuns};return this.trackRuntime;
  }
  addOpenRoad(pts,width,color){if(pts.length<2)return;const pos=[],idx=[];for(let i=0;i<pts.length;i++){const p=pts[i],prev=pts[Math.max(0,i-1)],next=pts[Math.min(pts.length-1,i+1)],dx=next.x-prev.x,dz=next.z-prev.z,l=Math.hypot(dx,dz)||1,nx=-dz/l,nz=dx/l;pos.push(p.x+nx*width/2,p.y+.025,p.z+nz*width/2,p.x-nx*width/2,p.y+.025,p.z-nz*width/2)}for(let i=0;i<pts.length-1;i++){const a=i*2,b=a+1,c=(i+1)*2,d=c+1;idx.push(a,b,c,b,d,c)}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));g.setIndex(idx);g.computeVertexNormals();this.roadRoot.add(new THREE.Mesh(g,new THREE.MeshStandardMaterial({color,roughness:.94,side:THREE.DoubleSide})))}
  addSceneryZone(z){const c=z.center||[0,0,0],type=z.type||'district',scale=+z.scale||1;const palette={downtown:'#526676',industrial:'#665d54',stadium:'#68717a',campus:'#697b65',waterfront:'#58748a',hills:'#536247',suburb:'#786c61',port:'#5d6570',interchange:'#64717b'};const count=type==='downtown'?22:type==='suburb'?14:10;for(let i=0;i<count;i++){const a=(i*2.399),r=(12+(i%5)*7)*scale,x=c[0]+Math.cos(a)*r,zp=c[2]+Math.sin(a)*r,h=(type==='downtown'?8+(i%7)*5:3+(i%5)*2)*scale;const m=new THREE.Mesh(new THREE.BoxGeometry((4+(i%3)*2)*scale,h,(4+((i+1)%3)*2)*scale),new THREE.MeshStandardMaterial({color:palette[type]||'#56616b',roughness:.88}));m.position.set(x,h/2+(c[1]||0),zp);this.roadRoot.add(m)}}
  addRamp(r){const p=r.position||[0,0,0],s=r.scale||[6,.8,9],type=r.type||'normal';const mesh=new THREE.Mesh(new THREE.BoxGeometry(s[0],s[1],s[2]),new THREE.MeshStandardMaterial({color:type==='curved'?'#725b7b':type==='inclined'?'#61798a':'#666d74',roughness:.65}));mesh.position.set(p[0],p[1]+s[1]/2,p[2]);mesh.rotation.order='YXZ';mesh.rotation.y=rad(r.rotation_y||0);mesh.rotation.x=rad(type==='inclined'?13:type==='curved'?10:8);this.roadRoot.add(mesh)}
  addTunnelFrame(pts,i,track,source=0){const p=pts[i],prev=pts[wrapIndex(i-1,pts.length)],next=pts[(i+1)%pts.length],yaw=Math.atan2(next.x-prev.x,next.z-prev.z),w=this.profileWidth(track,source);const mat=new THREE.MeshStandardMaterial({color:'#46545d',roughness:.75});const g=new THREE.Group();for(const sx of [-1,1]){const post=new THREE.Mesh(new THREE.BoxGeometry(.45,5,.45),mat);post.position.set(sx*w*.52,2.5,0);g.add(post)}const roof=new THREE.Mesh(new THREE.BoxGeometry(w*1.08,.45,.45),mat);roof.position.y=5;g.add(roof);g.position.set(p.x,p.y,p.z);g.rotation.y=yaw;this.roadRoot.add(g)}
  createRacers(playerV,bots){this.clear(this.carRoot);this.playerMesh=this.makeCar(playerV);this.carRoot.add(this.playerMesh);this.botMeshes=bots.map(v=>{const m=this.makeCar(v);this.carRoot.add(m);return m})}
  render(dt){this.clock+=dt;if(this.mode==='menu'&&this.playerMesh){this.playerMesh.rotation.y=this.clock*.35}if(this.mode==='garage'&&this.playerMesh){this.playerMesh.rotation.y=this.clock*.5}this.renderer.render(this.scene,this.camera)}
}

class RaceGame{
  constructor(world){this.world=world;this.active=false;this.paused=false;this.track=null;this.route=null;this.keys=new Set();this.cameraMode=0;this.countdown=0;this.raceTime=0;this.player=null;this.bots=[];this.rhythm=null;this.lastRamp=-99;this.result=false;this.bindInput()}
  bindInput(){window.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();this.keys.add(e.code);if(!this.active)return;if(e.code==='Escape'){e.preventDefault();togglePause()}if(e.code==='KeyH'){this.paused=true;showScreen('guide')}if(e.code==='KeyE'&&!e.repeat)this.startSwitch();if(e.code==='KeyM'&&!e.repeat)this.startRemix();if(['KeyJ','KeyK','KeyL','KeyI'].includes(e.code)&&!e.repeat)this.hitRhythm(['KeyJ','KeyK','KeyL','KeyI'].indexOf(e.code));if(e.code==='KeyC'&&!e.repeat)this.cameraMode=(this.cameraMode+1)%3;if(e.code==='KeyR'&&!e.repeat)this.respawn()});window.addEventListener('keyup',e=>{this.keys.delete(e.code);if(this.active&&e.code==='AltLeft')this.releaseRam()})}
  setup(track,a,b,settings,custom=false){audio.wake();this.track=track;this.route=this.world.buildTrack(track);const botVs=[];for(let i=0;i<5;i++)botVs.push(VEHICLES[(i+2)%VEHICLES.length]);this.world.createRacers(a,botVs);const p0=this.route.points[0],p1=this.route.points[1],yaw=Math.atan2(p1.x-p0.x,p1.z-p0.z);this.player={a,b,activeIndex:0,transform:false,t:0,cooldown:0,duration:+settings.duration,cooldownSet:+settings.cooldown,x:p0.x,y:p0.y+.55,z:p0.z,yaw,speed:0,routeIndex:0,lap:1,health:a.max_health,timeCharge:(a.advanced?.time_control?.max_time||3),timeDelay:0,ramCharge:0,ramArmed:0,ramDamage:1,n1:35,n2:0,n3:0,nitroStage:'none',remixTimer:0,turboTimer:0,turboIntensity:0,slipstream:false};this.bots=botVs.map((v,i)=>({v,progress:(i+1)*5,speed:4+i*.35,health:v.max_health,lane:(i%3-1)*2.3}));this.world.botMeshes.forEach((m,i)=>{const q=this.route.points[Math.floor(this.bots[i].progress)%this.route.points.length];m.position.set(q.x,q.y+.55,q.z)});this.active=true;this.paused=false;this.result=false;this.countdown=3.2;this.raceTime=0;this.rhythm={next:1.0,notes:[],combo:0,judge:'',judgeTimer:0,remix:false,remixEnd:0};this._custom=custom;this.lastRamp=-99;this.updateHud(true);showScreen('raceHud');$('#trackNameHud').textContent=track.name;$('#countdown').textContent='3';}
  stats(){const p=this.player;if(!p.transform)return interpolateVehicle(p.activeIndex?p.b:p.a,p.activeIndex?p.b:p.a,0);const source=p.activeIndex?p.b:p.a,target=p.activeIndex?p.a:p.b,t=smoothstep(p.t);return interpolateVehicle(source,target,t)}
  pairCoefficients(){const p=this.player;if(!p.transform)return p.activeIndex?[0,1]:[1,0];const t=smoothstep(p.t);return p.activeIndex?[t,1-t]:[1-t,t]}
  startSwitch(){const p=this.player;if(!p||p.transform||p.cooldown>0)return;p.transform=true;p.t=0;audio.tone(260,.09,'sawtooth',.12);toast('SWITCH')}
  updateSwitch(dt){const p=this.player;if(p.cooldown>0)p.cooldown=Math.max(0,p.cooldown-dt);if(!p.transform)return;p.t+=dt/Math.max(.05,p.duration);if(p.t>=1){p.transform=false;p.t=0;p.activeIndex=1-p.activeIndex;p.cooldown=p.cooldownSet;p.speed*=.82;audio.tone(480,.08,'square',.09)}}
  startRemix(){const p=this.player;if(p.nitroStage==='turbo'||p.n2<5||this.rhythm.remix)return;p.n2=0;p.nitroStage='remix';p.remixTimer=5+Math.random()*10;p.n3=0;this.rhythm.remix=true;this.rhythm.remixEnd=this.raceTime+p.remixTimer;this.rhythm.next=this.raceTime+.25;toast(`REMIX ${p.remixTimer.toFixed(1)} s`);audio.tone(660,.18,'sawtooth',.13)}
  finishRemix(){const p=this.player;this.rhythm.remix=false;if(p.n3<=.1){p.nitroStage='none';return}p.turboIntensity=clamp(p.n3/100,.05,1);p.turboTimer=lerp(BALANCE.nitro.turbo_min_seconds,BALANCE.nitro.turbo_max_seconds,p.turboIntensity);p.n3=0;p.nitroStage='turbo';document.body.classList.add('turbo');toast(`TURBO ${Math.round(p.turboIntensity*100)}%`);audio.tone(110,.3,'sawtooth',.18)}
  releaseRam(){const p=this.player,st=this.stats();if(p.ramCharge<.05)return;const ratio=clamp(p.ramCharge/Math.max(.25,st.ram_max_time),0,1);p.ramCharge=0;p.ramArmed=.78;p.ramDamage=lerp(1,st.ram_damage_multiplier,ratio);p.speed+=BALANCE.ram.lunge_world_speed*(.35+.65*ratio);toast(`EMBESTIDA ${Math.round(ratio*100)}%`);audio.tone(95,.16,'square',.18)}
  respawn(){const i=this.player.routeIndex,p=this.route.points[i],n=this.route.points[(i+1)%this.route.points.length];this.player.x=p.x;this.player.y=p.y+.55;this.player.z=p.z;this.player.yaw=Math.atan2(n.x-p.x,n.z-p.z);this.player.speed=0;toast('REAPARICIÓN')}
  nearestRoute(x,z,last=0){const pts=this.route.points,n=pts.length;let best=last,bestD=Infinity;const span=35;for(let d=-span;d<=span;d++){const i=wrapIndex(last+d,n),p=pts[i],dd=(x-p.x)**2+(z-p.z)**2;if(dd<bestD){bestD=dd;best=i}}if(bestD>2500){for(let i=0;i<n;i+=2){const p=pts[i],dd=(x-p.x)**2+(z-p.z)**2;if(dd<bestD){bestD=dd;best=i}}}return{index:best,distance:Math.sqrt(bestD)}}
  roadWidth(i){return this.world.profileWidth(this.track,this.route.source[i])}
  update(dt){if(!this.active||this.paused||this.result)return;const p=this.player;this.raceTime+=dt;audio.update(dt,p.nitroStage==='turbo');if(this.countdown>0){this.countdown-=dt;const c=this.countdown>2.2?'3':this.countdown>1.2?'2':this.countdown>.2?'1':'CONTRA!';$('#countdown').textContent=c;if(this.countdown<=0)$('#countdown').textContent='';this.updateCamera(dt);this.updateHud();return}
    const tcReq=this.keys.has('KeyQ'),st0=this.stats();const cap=st0.time_control_max;if(tcReq&&p.timeCharge>0){p.timeCharge=Math.max(0,p.timeCharge-dt);p.timeDelay=BALANCE.time_control.recharge_delay;document.body.classList.add('time-control')}else{document.body.classList.remove('time-control');p.timeDelay=Math.max(0,p.timeDelay-dt);if(p.timeDelay<=0)p.timeCharge=Math.min(cap,p.timeCharge+dt*BALANCE.time_control.recharge_rate)}
    const worldDt=tcReq&&p.timeCharge>0?dt*BALANCE.time_control.world_time_scale:dt;
    this.updateSwitch(dt);const st=this.stats();const throttle=this.keys.has('KeyW')||this.keys.has('ArrowUp'),brake=this.keys.has('KeyS')||this.keys.has('ArrowDown'),left=this.keys.has('KeyA')||this.keys.has('ArrowLeft'),right=this.keys.has('KeyD')||this.keys.has('ArrowRight'),hand=this.keys.has('Space'),ramHeld=this.keys.has('AltLeft'),baseNitro=this.keys.has('KeyN');
    if(ramHeld){p.ramCharge=Math.min(st.ram_max_time,p.ramCharge+dt);if(p.ramCharge>=st.ram_max_time){this.releaseRam()}}
    if(p.ramArmed>0){p.ramArmed=Math.max(0,p.ramArmed-dt);if(p.ramArmed<=0){p.speed*=BALANCE.ram.miss_speed_retention;p.ramDamage=1}}
    let top=st.top_speed*BALANCE.physics.speed_unit_scale,acc=(3.8+st.acceleration*.15),accMul=1,speedMul=1;
    const ramRatio=clamp(p.ramCharge/Math.max(.25,st.ram_max_time),0,1);if(ramHeld&&ramRatio>0){accMul*=lerp(1,st.ram_acceleration_multiplier,ramRatio);speedMul*=lerp(1,st.ram_top_speed_multiplier,ramRatio)}
    if(p.nitroStage==='none'&&baseNitro&&p.n1>0)p.nitroStage='base';if(p.nitroStage==='base'){if(baseNitro&&p.n1>0){p.n1=Math.max(0,p.n1-BALANCE.nitro.base_drain_per_second*dt);accMul*=st.nitro_base_acceleration_multiplier;speedMul*=st.nitro_base_speed_multiplier}else p.nitroStage='none'}
    if(p.nitroStage==='remix'){p.remixTimer-=dt;accMul*=st.nitro_remix_acceleration_multiplier;speedMul*=st.nitro_remix_speed_multiplier;if(p.remixTimer<=0)this.finishRemix()}
    if(p.nitroStage==='turbo'){p.turboTimer-=dt;accMul*=lerp(1,st.nitro_turbo_acceleration_multiplier,p.turboIntensity);speedMul*=lerp(1,st.nitro_turbo_speed_multiplier,p.turboIntensity);if(p.turboTimer<=0){p.nitroStage='none';p.turboIntensity=0;document.body.classList.remove('turbo')}}
    speedMul=Math.min(speedMul,BALANCE.nitro.max_combined_speed_multiplier);top*=speedMul;if(tcReq&&p.timeCharge>0){top*=BALANCE.time_control.speed_multiplier}
    const near=this.nearestRoute(p.x,p.z,p.routeIndex),roadW=this.roadWidth(near.index),off=near.distance>roadW*.52;const surface=this.world.surfaceFor(this.track,this.route.source[near.index]);let grip=st.grip*surface.grip*(off?.62:1);if(hand)grip*=BALANCE.physics.handbrake_grip_multiplier;if(tcReq&&p.timeCharge>0)grip*=BALANCE.time_control.grip_multiplier;
    if(throttle){const ratio=clamp(Math.abs(p.speed)/Math.max(top,.001),0,1.5),torque=Math.max(.12,1-ratio**1.7);p.speed+=acc*accMul*torque*dt}if(brake){if(p.speed>.15)p.speed-=(5+st.braking*.22)*(tcReq?BALANCE.time_control.braking_multiplier:1)*dt;else p.speed-=acc*.55*dt}
    const drag=BALANCE.physics.rolling_drag*(off?BALANCE.physics.offroad_drag_multiplier:1)+BALANCE.physics.air_drag*p.speed*p.speed;p.speed-=Math.sign(p.speed)*Math.min(Math.abs(p.speed),drag*dt);p.speed=clamp(p.speed,-top*BALANCE.physics.reverse_ratio,top*1.05);
    let steer=(right?1:0)-(left?1:0),steerFactor=lerp(BALANCE.physics.minimum_steering_factor,1,clamp(1-Math.abs(p.speed)/(top*1.15),0,1));let controlMul=tcReq&&p.timeCharge>0?st.time_control_control_multiplier:1;let yawRate=rad(BALANCE.physics.steering_speed)*steer*steerFactor*(.4+st.control/100*.75)*grip*controlMul*(hand?1.35:1);p.yaw+=yawRate*dt*Math.sign(p.speed||1);
    const fwd={x:Math.sin(p.yaw),z:Math.cos(p.yaw)};p.x+=fwd.x*p.speed*dt;p.z+=fwd.z*p.speed*dt;p.routeIndex=near.index;const rp=this.route.points[near.index];p.y=lerp(p.y,rp.y+.55,clamp(dt*10,0,1));
    this.updateSlipstream(dt,st,fwd);this.updateRamps(dt);this.updateBots(worldDt);this.handleCollisions(st);this.updateRhythm(dt);this.updateLap(near.index);this.updateCamera(dt);this.updateMeshes(st);this.updateHud();
  }
  updateSlipstream(dt,st,fwd){const p=this.player;let active=false;for(const b of this.bots){const bi=Math.floor(b.progress)%this.route.points.length,q=this.route.points[bi],dx=q.x-p.x,dz=q.z-p.z,d=Math.hypot(dx,dz);if(d<3||d>BALANCE.slipstream.distance)continue;const dot=(dx*fwd.x+dz*fwd.z)/d;if(dot>Math.cos(rad(BALANCE.slipstream.angle))&&p.speed>BALANCE.slipstream.minimum_speed){active=true;p.speed+=BALANCE.slipstream.acceleration_world*dt*.25;const passive=p.activeIndex?p.b.passive:p.a.passive,mul=passive?.id==='slipstream'?1+(passive.value||0):1;p.n1=clamp(p.n1+BALANCE.slipstream.nitro_per_second*mul*dt,0,100);break}}p.slipstream=active}
  updateRamps(dt){const p=this.player;for(let i=0;i<(this.track.ramps||[]).length;i++){const r=this.track.ramps[i],q={x:r.position[0],z:r.position[2]},d=Math.hypot(p.x-q.x,p.z-q.z);if(d<6&&this.raceTime-this.lastRamp>2){this.lastRamp=this.raceTime;const reward=r.type==='curved'?BALANCE.nitro.curved_ramp_reward:r.type==='inclined'?BALANCE.nitro.inclined_ramp_reward:BALANCE.nitro.ramp_reward;p.n1=clamp(p.n1+reward,0,100);p.y+=1.3;p.speed+=1.2;toast(`${r.type==='curved'?'BARREL ROLL':r.type==='inclined'?'RAMP INCLINADA':'SALTO'} +NITRO`)}}
    const src=this.route.source[p.routeIndex],inTunnel=(this.track.tunnel_segments||[]).includes(src);if(inTunnel)p.n1=clamp(p.n1+BALANCE.nitro.tunnel_per_second*dt,0,100)}
  updateBots(dt){const n=this.route.points.length;for(let i=0;i<this.bots.length;i++){const b=this.bots[i],v=b.v;b.speed+=(3.8+v.acceleration*.12)*dt*.28;b.speed=Math.min(b.speed,v.top_speed*BALANCE.physics.speed_unit_scale*.82);b.progress+=b.speed*dt*(n/780);const idx=Math.floor(b.progress)%n,frac=b.progress%1,p=this.route.points[idx],q=this.route.points[(idx+1)%n],prev=this.route.points[wrapIndex(idx-1,n)],next=this.route.points[(idx+1)%n],dx=next.x-prev.x,dz=next.z-prev.z,l=Math.hypot(dx,dz)||1,nx=-dz/l,nz=dx/l;const x=lerp(p.x,q.x,frac)+nx*b.lane,z=lerp(p.z,q.z,frac)+nz*b.lane,y=lerp(p.y,q.y,frac)+.55,m=this.world.botMeshes[i];m.position.set(x,y,z);m.rotation.y=Math.atan2(q.x-p.x,q.z-p.z)}}
  handleCollisions(st){const p=this.player;for(let i=0;i<this.bots.length;i++){const m=this.world.botMeshes[i],d=Math.hypot(m.position.x-p.x,m.position.z-p.z);if(d<2.1){const impact=Math.abs(p.speed-this.bots[i].speed);if(impact>2){const dmg=Math.max(0,(impact-BALANCE.damage.minimum_impact_speed)*BALANCE.damage.damage_scale)*(1+st.robustness/100)*p.ramDamage;this.bots[i].health-=dmg*9;p.health-=Math.max(.5,dmg*4*(1-this.bots[i].v.resistance/160));if(p.ramArmed>0){p.ramArmed=0;p.ramDamage=1;p.speed*=BALANCE.ram.impact_speed_retention;this.bots[i].speed*=.65;toast('¡IMPACTO DE EMBESTIDA!')}else p.speed*=.86;audio.tone(70,.08,'square',.1)}}}if(p.health<=0){p.health=(p.activeIndex?p.b:p.a).max_health*.7;this.respawn()}}
  updateRhythm(dt){const r=this.rhythm;if(r.judgeTimer>0){r.judgeTimer-=dt;if(r.judgeTimer<=0)r.judge=''}const interval=r.remix?.34:.72;if(this.raceTime>=r.next){r.next=this.raceTime+interval*(.8+Math.random()*.45);r.notes.push({lane:Math.floor(Math.random()*4),time:this.raceTime+1.45,hit:false})}r.notes=r.notes.filter(n=>this.raceTime-n.time<.35&&!n.hit);if(r.remix&&this.raceTime>=r.remixEnd)this.finishRemix();this.drawRhythm()}
  hitRhythm(lane){if(!this.active||this.paused||this.countdown>0)return;const r=this.rhythm,p=this.player;let best=null,bestAbs=Infinity;for(const n of r.notes){if(n.lane!==lane||n.hit)continue;const d=Math.abs(this.raceTime-n.time);if(d<bestAbs){bestAbs=d;best=n}}if(!best||bestAbs>.18){r.combo=0;r.judge='MISS';r.judgeTimer=.5;audio.tone(120,.06,'square',.04);return}best.hit=true;let energy,label;if(bestAbs<=.05){energy=2.2;label='PERFECT'}else if(bestAbs<=.10){energy=1.45;label='EXCELLENT'}else{energy=.8;label='GOOD'}r.combo++;r.judge=`${label} ×${r.combo}`;r.judgeTimer=.55;if(r.remix)p.n3=clamp(p.n3+energy*BALANCE.nitro.sequence_b_energy_scale,0,100);else{let e=energy*BALANCE.nitro.sequence_a_energy_scale,room=100-p.n1,add=Math.min(room,e);p.n1+=add;e-=add;p.n2=clamp(p.n2+e,0,100)}audio.tone([330,390,440,520][lane],.055,'triangle',.08)}
  drawRhythm(){const lanes=$('#rhythmLanes');if(!lanes.dataset.ready){lanes.innerHTML='<div class="lane"></div><div class="lane"></div><div class="lane"></div><div class="lane"></div><div class="hit-line"></div>';lanes.dataset.ready='1'}$$('.lane',lanes).forEach(x=>x.innerHTML='');for(const n of this.rhythm.notes){const d=n.time-this.raceTime;if(d<-.3||d>1.55)continue;const el=document.createElement('div');el.className='note';el.style.bottom=`${20+clamp(1-d/1.45,0,1)*210}px`;$$('.lane',lanes)[n.lane].append(el)}$('#rhythmJudge').textContent=this.rhythm.judge;$('#rhythmPanel').classList.toggle('hidden',this.player.nitroStage==='turbo');$('.rhythm-title').textContent=this.rhythm.remix?'REMIX SEQUENCE B':'TRACK SEQUENCE A'}
  updateLap(idx){const p=this.player,n=this.route.points.length,prev=p._prevIdx??idx;if(prev>n*.82&&idx<n*.18){p.lap++;if(p.lap>+(this.track.laps||3)){this.finishRace();return}}p._prevIdx=idx}
  finishRace(){this.result=true;this.active=false;document.body.classList.remove('turbo','time-control');$('#resultTitle').textContent='META';$('#resultText').textContent=`Tiempo ${fmtTime(this.raceTime)} · ${this.track.name}`;showScreen('result')}
  updateCamera(dt){const p=this.player;if(!p||!this.world.playerMesh)return;const f={x:Math.sin(p.yaw),z:Math.cos(p.yaw)},cam=this.world.camera;let target;if(this.cameraMode===0)target=new THREE.Vector3(p.x-f.x*10,p.y+4.6,p.z-f.z*10);else if(this.cameraMode===1)target=new THREE.Vector3(p.x-f.x*5,p.y+2.4,p.z-f.z*5);else target=new THREE.Vector3(p.x+10,p.y+9,p.z-10);cam.position.lerp(target,1-Math.pow(.0008,dt));cam.lookAt(p.x+f.x*5,p.y+1,p.z+f.z*5);const targetFov=this.player.nitroStage==='turbo'?76:66;cam.fov=lerp(cam.fov,targetFov,clamp(dt*5,0,1));cam.updateProjectionMatrix()}
  updateMeshes(){const p=this.player,m=this.world.playerMesh;m.position.set(p.x,p.y,p.z);m.rotation.y=p.yaw;const source=p.activeIndex?p.b:p.a,target=p.activeIndex?p.a:p.b,t=p.transform?smoothstep(p.t):0;this.world.updateCarMorph(m,source,target,t)}
  updateHud(){const p=this.player;if(!p)return;const st=this.stats(),co=this.pairCoefficients();$('#speedText').innerHTML=`${String(Math.round(Math.max(0,p.speed/BALANCE.physics.speed_unit_scale))).padStart(3,'0')} <small>km/h</small>`;$('#switchText').textContent=`${p.a.name} ${co[0].toFixed(2)}  +  ${p.b.name} ${co[1].toFixed(2)}${p.transform?'  |  TRANSFORMANDO':''}`;$('#lapText').textContent=`VUELTA ${Math.min(p.lap,this.track.laps||3)}/${this.track.laps||3}`;$('#timeText').textContent=fmtTime(this.raceTime);$('#timeBar').style.width=`${clamp(p.timeCharge/st.time_control_max*100,0,100)}%`;$('#ramBar').style.width=`${clamp(p.ramCharge/st.ram_max_time*100,0,100)}%`;$('#n1').style.width=`${p.n1}%`;$('#n2').style.width=`${p.n2}%`;$('#n3').style.width=`${p.nitroStage==='turbo'?p.turboIntensity*100:p.n3}%`;$('#healthBar').style.width=`${clamp(p.health/st.max_health*100,0,100)}%`;$('#statusText').textContent=p.slipstream?'REBUFO + NITRO':p.nitroStage==='turbo'?'TURBO NITRO':p.nitroStage==='remix'?'REMIX NITRO':p.ramArmed>0?'EMBESTIDA ARMADA':'';this.updateMinimap()}
  updateMinimap(){const c=$('#minimap'),ctx=c.getContext('2d'),pts=this.route.points,w=c.width,h=c.height;ctx.clearRect(0,0,w,h);const xs=pts.map(p=>p.x),zs=pts.map(p=>p.z),minx=Math.min(...xs),maxx=Math.max(...xs),minz=Math.min(...zs),maxz=Math.max(...zs),pad=12,s=Math.min((w-pad*2)/(maxx-minx||1),(h-pad*2)/(maxz-minz||1)),map=p=>[pad+(p.x-minx)*s,h-(pad+(p.z-minz)*s)];ctx.strokeStyle='#9cb0bd';ctx.lineWidth=2;ctx.beginPath();pts.forEach((p,i)=>{const [x,y]=map(p);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.closePath();ctx.stroke();for(const b of this.bots){const q=pts[Math.floor(b.progress)%pts.length],[x,y]=map(q);ctx.fillStyle='#ff6c59';ctx.beginPath();ctx.arc(x,y,2.5,0,TAU);ctx.fill()}const [px,py]=map(this.player);ctx.fillStyle='#13aaff';ctx.beginPath();ctx.arc(px,py,4,0,TAU);ctx.fill()}
}

class TrackMaker{
  constructor(canvas){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.tool='select';this.points=[];this.checkpoints=new Set([0]);this.ramps=[];this.tunnels=new Set();this.selected=-1;this.drag=false;this.panDrag=false;this.pan={x:0,y:0};this.zoom=2;this.elev=0;this.width=14;this.undo=[];this.redo=[];this.resize();this.newTrack();window.addEventListener('resize',()=>this.resize());this.bind()}
  resize(){const r=this.canvas.getBoundingClientRect();this.canvas.width=Math.max(1,Math.floor(r.width*devicePixelRatio));this.canvas.height=Math.max(1,Math.floor(r.height*devicePixelRatio));this.ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);this.draw()}
  newTrack(){this.points=[[-45,0,-20],[-20,0,35],[25,2,45],[55,0,5],[30,0,-40],[-15,0,-48]];this.checkpoints=new Set([0,2,4]);this.ramps=[];this.tunnels=new Set();this.selected=0;this.undo=[];this.redo=[];this.pan={x:0,y:0};this.zoom=2;this.changed=true;this.draw();this.status('Nueva pista')}
  snapshot(){return JSON.stringify({points:this.points,checkpoints:[...this.checkpoints],ramps:this.ramps,tunnels:[...this.tunnels],width:this.width})}
  restore(s){const d=JSON.parse(s);this.points=d.points;this.checkpoints=new Set(d.checkpoints);this.ramps=d.ramps||[];this.tunnels=new Set(d.tunnels||[]);this.width=d.width||14;$('#makerWidth').value=this.width;this.draw()}
  push(){this.undo.push(this.snapshot());if(this.undo.length>100)this.undo.shift();this.redo=[]}
  doUndo(){if(!this.undo.length)return;this.redo.push(this.snapshot());this.restore(this.undo.pop());this.status('Undo')}
  doRedo(){if(!this.redo.length)return;this.undo.push(this.snapshot());this.restore(this.redo.pop());this.status('Redo')}
  status(t){$('#makerStatus').textContent=t}
  bind(){
    $$('[data-tool]').forEach(b=>b.addEventListener('click',()=>{this.tool=b.dataset.tool;$$('[data-tool]').forEach(x=>x.classList.toggle('active',x===b));this.status(`Herramienta: ${b.textContent}`)}));
    this.canvas.addEventListener('wheel',e=>{e.preventDefault();const old=this.screenToWorld(e.offsetX,e.offsetY);this.zoom=clamp(this.zoom*(e.deltaY<0?1.12:.89),.35,7);const neu=this.worldToScreen(old.x,old.z);this.pan.x+=e.offsetX-neu.x;this.pan.y+=e.offsetY-neu.y;this.draw()},{passive:false});
    this.canvas.addEventListener('mousedown',e=>{if(e.button===1){this.panDrag=true;this._last={x:e.clientX,y:e.clientY};return}if(e.button!==0)return;const w=this.screenToWorld(e.offsetX,e.offsetY),idx=this.nearest(w.x,w.z);if(this.tool==='select'){this.selected=idx;if(idx>=0){this.push();this.drag=true}}else if(this.tool==='draw'){this.push();if(idx>=0&&dist2({x:w.x,z:w.z},{x:this.points[idx][0],z:this.points[idx][2]})<7/this.zoom){this.selected=idx}else{let insert=this.closestSegment(w.x,w.z);this.points.splice(insert+1,0,[w.x,this.elev,w.z]);this.remapOnInsert(insert+1);this.selected=insert+1;this.changed=true}}else if(this.tool==='checkpoint'&&idx>=0){this.push();this.checkpoints.has(idx)?(idx!==0&&this.checkpoints.delete(idx)):this.checkpoints.add(idx);this.changed=true}else if(this.tool==='ramp'){this.push();this.ramps.push({id:`maker_ramp_${Date.now()}`,type:'normal',position:[w.x,this.elev,w.z],rotation_y:0,scale:[6,.7,8]});this.changed=true}else if(this.tool==='tunnel'&&idx>=0){this.push();this.tunnels.has(idx)?this.tunnels.delete(idx):this.tunnels.add(idx);this.changed=true}else if(this.tool==='delete'&&idx>0){this.push();this.deletePoint(idx)}this.draw()});
    window.addEventListener('mousemove',e=>{if(this.panDrag){this.pan.x+=e.clientX-this._last.x;this.pan.y+=e.clientY-this._last.y;this._last={x:e.clientX,y:e.clientY};this.draw()}else if(this.drag&&this.selected>=0){const r=this.canvas.getBoundingClientRect(),w=this.screenToWorld(e.clientX-r.left,e.clientY-r.top);this.points[this.selected][0]=w.x;this.points[this.selected][2]=w.z;this.points[this.selected][1]=this.elev;this.changed=true;this.draw()}});window.addEventListener('mouseup',e=>{if(e.button===1)this.panDrag=false;if(e.button===0)this.drag=false});
    window.addEventListener('keydown',e=>{if(!$('#maker').classList.contains('active'))return;if(e.ctrlKey&&e.code==='KeyZ'){e.preventDefault();this.doUndo()}if(e.ctrlKey&&e.code==='KeyY'){e.preventDefault();this.doRedo()}if(e.code==='Delete'&&this.selected>0){this.push();this.deletePoint(this.selected);this.draw()}if(/^Digit[1-6]$/.test(e.code)){const tools=['select','draw','checkpoint','ramp','tunnel','delete'];const t=tools[+e.code.at(-1)-1];$(`[data-tool="${t}"]`)?.click()}});
    $('#makerUndo').onclick=()=>this.doUndo();$('#makerRedo').onclick=()=>this.doRedo();$('#makerWidth').oninput=e=>{this.width=+e.target.value;this.draw()};$('#makerElevation').onchange=e=>{this.elev=+e.target.value;if(this.selected>=0&&this.tool==='select'){this.push();this.points[this.selected][1]=this.elev;this.changed=true;this.draw()}};$('#makerNew').onclick=()=>this.newTrack();$('#makerSave').onclick=()=>this.save();$('#makerLoad').onclick=()=>this.load();$('#makerExport').onclick=()=>this.export();$('#makerPlay').onclick=()=>{if(this.points.length<4){toast('Necesitas al menos 4 nodos');return}startRace(this.toTrack(),true)};
  }
  remapOnInsert(k){this.checkpoints=new Set([...this.checkpoints].map(i=>i>=k?i+1:i));this.tunnels=new Set([...this.tunnels].map(i=>i>=k?i+1:i))}
  deletePoint(k){if(k<=0||this.points.length<=4)return;this.points.splice(k,1);const map=s=>new Set([...s].filter(i=>i!==k).map(i=>i>k?i-1:i));this.checkpoints=map(this.checkpoints);this.tunnels=map(this.tunnels);this.checkpoints.add(0);this.selected=Math.min(k,this.points.length-1);this.changed=true}
  nearest(x,z){let best=-1,d=Infinity;this.points.forEach((p,i)=>{const q=Math.hypot(x-p[0],z-p[2]);if(q<d){d=q;best=i}});return d<8/this.zoom?best:-1}
  closestSegment(x,z){let best=0,bd=Infinity;for(let i=0;i<this.points.length;i++){const a=this.points[i],b=this.points[(i+1)%this.points.length],vx=b[0]-a[0],vz=b[2]-a[2],l2=vx*vx+vz*vz||1,t=clamp(((x-a[0])*vx+(z-a[2])*vz)/l2,0,1),px=a[0]+vx*t,pz=a[2]+vz*t,d=(x-px)**2+(z-pz)**2;if(d<bd){bd=d;best=i}}return best}
  worldToScreen(x,z){const r=this.canvas.getBoundingClientRect();return{x:r.width/2+this.pan.x+x*this.zoom,y:r.height/2+this.pan.y-z*this.zoom}}
  screenToWorld(x,y){const r=this.canvas.getBoundingClientRect();return{x:(x-r.width/2-this.pan.x)/this.zoom,z:-(y-r.height/2-this.pan.y)/this.zoom}}
  draw(){if(!this.ctx)return;const r=this.canvas.getBoundingClientRect(),ctx=this.ctx;ctx.clearRect(0,0,r.width,r.height);ctx.save();ctx.strokeStyle='rgba(70,135,175,.12)';ctx.lineWidth=1;const grid=20*this.zoom;for(let x=(r.width/2+this.pan.x)%grid;x<r.width;x+=grid){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,r.height);ctx.stroke()}for(let y=(r.height/2+this.pan.y)%grid;y<r.height;y+=grid){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(r.width,y);ctx.stroke()}ctx.restore();if(this.points.length>1){ctx.lineJoin='round';ctx.lineCap='round';ctx.strokeStyle='#263845';ctx.lineWidth=this.width*this.zoom;ctx.beginPath();this.points.forEach((p,i)=>{const s=this.worldToScreen(p[0],p[2]);i?ctx.lineTo(s.x,s.y):ctx.moveTo(s.x,s.y)});ctx.closePath();ctx.stroke();ctx.strokeStyle='#758a99';ctx.lineWidth=1.5;ctx.stroke()}for(let i=0;i<this.points.length;i++){const p=this.points[i],s=this.worldToScreen(p[0],p[2]);ctx.fillStyle=i===this.selected?'#ffe600':this.checkpoints.has(i)?'#53ff78':'#1ea9ff';ctx.beginPath();ctx.arc(s.x,s.y,i===this.selected?7:5,0,TAU);ctx.fill();ctx.fillStyle='#dbeeff';ctx.font='11px Segoe UI';ctx.fillText(`${i}${p[1]?` · ${p[1]}m`:''}`,s.x+8,s.y-7);if(this.tunnels.has(i)){ctx.strokeStyle='#c08cff';ctx.lineWidth=3;ctx.beginPath();ctx.arc(s.x,s.y,11,0,TAU);ctx.stroke()}}for(const q of this.ramps){const s=this.worldToScreen(q.position[0],q.position[2]);ctx.fillStyle='#ff8a33';ctx.fillRect(s.x-6,s.y-4,12,8)}}
  toTrack(){return{id:'maker_track',name:'Mi Circuito Maker',description:'Circuito creado en ContraDrivers Web Track Maker',style:'maker',difficulty:3,width:this.width,laps:3,lane_count:2,environment:{sky_color:'#6d91a4',terrain_color:'#345c43'},route_smoothing:{samples_per_segment:5,tension:.58},waypoints:copy(this.points),checkpoint_indices:[...this.checkpoints].sort((a,b)=>a-b),surfaces:[{name:'maker_asphalt',from:0,to:this.points.length-1,grip:1,color:'#34383d'}],barrier_ranges:[],combat_sector:[0,Math.max(1,this.points.length-1)],obstacles:[],playlist:['web_rhythm'],tunnel_segments:[...this.tunnels],ramps:copy(this.ramps),alternate_roads:[],scenery_zones:[{type:'downtown',center:[0,0,0],scale:.7}],road_profiles:[{from:0,to:this.points.length-1,class:'maker_road',width:this.width,lanes:2}]}}
  save(){localStorage.setItem('contradrivers:maker',this.snapshot());this.changed=false;this.status('Guardado en este navegador');toast('PISTA GUARDADA')}
  load(){const s=localStorage.getItem('contradrivers:maker');if(!s){toast('No hay pista guardada');return}this.push();this.restore(s);this.changed=false;this.status('Pista cargada')}
  export(){const blob=new Blob([JSON.stringify(this.toTrack(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='contradrivers_maker_track.json';a.click();URL.revokeObjectURL(a.href);this.status('JSON exportado')}
}

let world,race,maker;
try{world=new ThreeWorld($('#gameCanvas'));race=new RaceGame(world);maker=new TrackMaker($('#makerCanvas'))}catch(error){console.error(error);$('#fatal').hidden=false;$('#fatalText').textContent=error?.message||String(error);throw error}
let currentScreen='menu',previousScreen='menu',selectedTrack=0;
const settings=Object.assign({a:'pocket_comet',b:'beetle_nova',duration:1,cooldown:.3},JSON.parse(localStorage.getItem('contradrivers:web:settings')||'{}'));
function saveSettings(){localStorage.setItem('contradrivers:web:settings',JSON.stringify(settings))}
function V(id){return VEHICLES.find(v=>v.id===id)||VEHICLES[0]}
function showScreen(name){previousScreen=currentScreen;currentScreen=name;$$('.screen').forEach(s=>s.classList.toggle('active',s.id===name));if(name==='menu')world.showMenuScene();if(name==='garage'){populateGarage();world.showGarage(V(settings.a),V(settings.b))}if(name==='maker'){maker.resize();race.paused=true}if(name==='raceHud')race.paused=false;if(name!=='raceHud'&&name!=='pause'&&name!=='guide')document.body.classList.remove('turbo','time-control')}
function togglePause(){if(!race.active)return;if(currentScreen==='pause'){showScreen('raceHud');race.paused=false}else{race.paused=true;showScreen('pause')}}
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');clearTimeout(toast._t);toast._t=setTimeout(()=>el.classList.remove('show'),1200)}
function populateGarage(){const a=$('#vehicleA'),b=$('#vehicleB');if(!a.options.length){for(const v of VEHICLES){a.add(new Option(v.name,v.id));b.add(new Option(v.name,v.id))}}a.value=settings.a;b.value=settings.b;$('#switchDuration').value=String(settings.duration);$('#switchCooldown').value=String(settings.cooldown);const va=V(settings.a),vb=V(settings.b);$('#garagePairTitle').textContent=`${va.name}  ↔  ${vb.name}`;const keys=[['Velocidad',`${va.top_speed} / ${vb.top_speed} km/h`],['Aceleración',`${va.acceleration} / ${vb.acceleration}`],['Control',`${va.control} / ${vb.control}`],['Resistencia',`${va.resistance} / ${vb.resistance}`],['Robustez',`${va.robustness} / ${vb.robustness}`],['Embestida',`${va.advanced.ram.max_time}s / ${vb.advanced.ram.max_time}s`],['Time Control',`${va.advanced.time_control.max_time}s / ${vb.advanced.time_control.max_time}s`]];$('#garageStats').innerHTML=keys.map(([k,v])=>`<div class="stat"><span>${k}</span><b>${v}</b></div>`).join('')}
function buildTrackCards(){const box=$('#trackCards');box.innerHTML=TRACKS.map((t,i)=>`<article class="track-card ${i===selectedTrack?'active':''}" data-track="${i}"><strong>${t.name}</strong><p>${t.description||''}</p><div class="eyebrow">${(t.tags||[]).slice(0,3).join(' · ')}</div></article>`).join('');$$('[data-track]').forEach(c=>c.onclick=()=>{selectedTrack=+c.dataset.track;buildTrackCards()})}
function startRace(track=null,custom=false){race.setup(track||TRACKS[selectedTrack],V(settings.a),V(settings.b),settings,custom)}

$$('[data-action]').forEach(b=>b.addEventListener('click',()=>{const a=b.dataset.action;if(a==='play'){buildTrackCards();showScreen('trackSelect')}else if(a==='garage')showScreen('garage');else if(a==='maker')showScreen('maker');else if(a==='guide'){race.paused=race.active;showScreen('guide')}else if(a==='back'){if(race.active&&(previousScreen==='raceHud'||previousScreen==='pause'||currentScreen==='guide'))showScreen('raceHud');else showScreen('menu')}else if(a==='resume'){showScreen('raceHud');race.paused=false}else if(a==='menu'){race.active=false;race.paused=false;showScreen('menu')}}));
$('#startRace').onclick=()=>startRace();
$('#vehicleA').onchange=e=>{settings.a=e.target.value;if(settings.a===settings.b)settings.b=VEHICLES.find(v=>v.id!==settings.a).id;saveSettings();populateGarage();world.showGarage(V(settings.a),V(settings.b))};
$('#vehicleB').onchange=e=>{settings.b=e.target.value;if(settings.b===settings.a)settings.a=VEHICLES.find(v=>v.id!==settings.b).id;saveSettings();populateGarage();world.showGarage(V(settings.a),V(settings.b))};
$('#switchDuration').onchange=e=>{settings.duration=+e.target.value;saveSettings()};$('#switchCooldown').onchange=e=>{settings.cooldown=+e.target.value;saveSettings()};

let prev=performance.now();function loop(now){const dt=Math.min(.05,(now-prev)/1000||0);prev=now;if(race.active&&currentScreen==='raceHud')race.update(dt);world.render(dt);requestAnimationFrame(loop)}requestAnimationFrame(loop);
buildTrackCards();populateGarage();window.addEventListener('pointerdown',()=>audio.wake(),{once:true});
