import {VEHICLES,TRACKS} from './game-data.js';
import {AAA} from './src/config.js';
import {InputManager,FixedStepper,AudioEngine,clamp,copy} from './src/core.js';
import {WorldRenderer,TrafficSystem} from './src/world.js';
import {SwitchSystem,NitroSystem,VehicleController,resolveTrafficInteractions} from './src/vehicle.js';
import {LevelBeatDirector,AIDriver,PursuitDirector,RhythmDirector,RaceDirector} from './src/directors.js';
import {CameraRig,HUD,ScreenManager} from './src/presentation.js';
import {TrackMaker} from './src/maker.js';

const $=q=>document.querySelector(q), $$=q=>[...document.querySelectorAll(q)];
class ContraDriversGame{
  constructor(){
    this.input=new InputManager();this.audio=new AudioEngine();this.screens=new ScreenManager();this.world=new WorldRenderer($('#gameCanvas'),AAA);this.camera=new CameraRig(this.world,AAA.camera);this.hud=new HUD();this.stepper=new FixedStepper(AAA.fixed_step,AAA.max_substeps);this.state='menu';this.trackIndex=0;this.vehicleA=1;this.vehicleB=3;this.switchDuration=1;this.switchCooldown=.3;this.last=performance.now();this._makerTrack=null;this.gameTime=0;this.bindUI();this.populateUI();this.maker=new TrackMaker($('#makerCanvas'),track=>this.startRace(track,true));this.world.showMenu(VEHICLES[this.vehicleA]);this.loop(this.last)}
  bindUI(){
    addEventListener('pointerdown',()=>this.audio.wake(),{once:true});
    $$('[data-action]').forEach(b=>b.addEventListener('click',()=>this.action(b.dataset.action)));
    $('#startRace').addEventListener('click',()=>this.startRace(TRACKS[this.trackIndex]));
    $('#vehicleA').addEventListener('change',e=>{this.vehicleA=+e.target.value;this.refreshGarage()});$('#vehicleB').addEventListener('change',e=>{this.vehicleB=+e.target.value;this.refreshGarage()});
    $('#switchDuration').addEventListener('change',e=>this.switchDuration=+e.target.value);$('#switchCooldown').addEventListener('change',e=>this.switchCooldown=+e.target.value);
    $('#makerPlay').addEventListener('click',()=>this.maker.play());$('#makerSave').addEventListener('click',()=>this.maker.save());$('#makerExport').addEventListener('click',()=>this.maker.export());$('#makerUndo').addEventListener('click',()=>this.maker.undo());$('#makerRedo').addEventListener('click',()=>this.maker.redo());$('#makerNew').addEventListener('click',()=>{this.maker.pushHistory();this.maker.doc=this.maker.defaultDoc();this.maker.status('Nueva pista')});$('#makerLoad').addEventListener('click',()=>this.maker.load());
    $$('[data-tool]').forEach(b=>b.addEventListener('click',()=>this.maker.setTool(b.dataset.tool)));$('#makerWidth').addEventListener('input',e=>{this.maker.doc.width=+e.target.value;for(const p of this.maker.doc.road_profiles||[])p.width=+e.target.value});$('#makerElevation').addEventListener('input',e=>{if(this.maker.selected>=0)this.maker.doc.waypoints[this.maker.selected][1]=+e.target.value});
    addEventListener('keydown',e=>{if(e.code==='Escape'){if(this.state==='race')this.pause();else if(this.state==='pause')this.resume()}if(e.code==='KeyH'&&this.state==='race'){this.pause();this.screens.show('guide')}if(e.code==='KeyC'&&this.state==='race')this.camera.cycle();if(e.code==='KeyR'&&this.state==='race')this.player.setStart(this.player.nearest)});
    $('#settingsTraffic')?.addEventListener('input',e=>{AAA.traffic.spawn_max=10+Math.round(+e.target.value*20)});$('#settingsShake')?.addEventListener('input',e=>{AAA.camera.shake_decay=4+10*(1-+e.target.value)});
  }
  populateUI(){const va=$('#vehicleA'),vb=$('#vehicleB');VEHICLES.forEach((v,i)=>{for(const s of [va,vb]){const o=document.createElement('option');o.value=i;o.textContent=v.name;s.append(o)}});va.value=this.vehicleA;vb.value=this.vehicleB;const cards=$('#trackCards');TRACKS.forEach((t,i)=>{const b=document.createElement('button');b.className='track-card';b.innerHTML=`<strong>${t.name}</strong><small>${t.aaa_profile?.theme||''}</small><span>${(t.aaa_profile?.districts||[]).join(' · ')}</span>`;b.addEventListener('click',()=>{this.trackIndex=i;$$('.track-card').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')});cards.append(b);if(i===0)b.classList.add('selected')});this.refreshGarage()}
  refreshGarage(){const a=VEHICLES[this.vehicleA],b=VEHICLES[this.vehicleB];$('#garagePairTitle').textContent=`${a.name} ↔ ${b.name}`;const rows=[['Punta',a.top_speed,b.top_speed,'km/h'],['Aceleración',a.acceleration,b.acceleration,''],['Control',a.control,b.control,''],['Resistencia',a.resistance,b.resistance,''],['Robustez',a.robustness,b.robustness,''],['Masa',a.mass,b.mass,'kg'],['Time Control',a.advanced.time_control.max_time,b.advanced.time_control.max_time,'s'],['RAM',a.advanced.ram.max_time,b.advanced.ram.max_time,'s']];$('#garageStats').innerHTML=rows.map(r=>`<div><span>${r[0]}</span><b>${r[1]}${r[3]}</b><i>↔</i><b>${r[2]}${r[3]}</b></div>`).join('');if(this.state==='garage')this.world.showGarage(a)}
  action(a){this.audio.wake();if(a==='play'){this.screens.show('trackSelect');this.state='menu'}else if(a==='garage'){this.state='garage';this.screens.show('garage');this.world.showGarage(VEHICLES[this.vehicleA])}else if(a==='maker'){this.state='maker';this.screens.show('maker');this.hud.show(false)}else if(a==='guide'){this.screens.show('guide')}else if(a==='back'){this.screens.back();if(this.screens.current==='menu'){this.state='menu';this.hud.show(false);this.world.showMenu(VEHICLES[this.vehicleA])}else if(this.screens.current==='garage'){this.state='garage';this.world.showGarage(VEHICLES[this.vehicleA])}else if(this.screens.current==='pause'){this.state='pause'}else if(this.screens.current==='raceHud'){this.state='race';this.hud.show(true)}else if(this.screens.current==='trackSelect'){this.state='menu'}}else if(a==='menu'){this.toMenu()}else if(a==='resume')this.resume()}
  startRace(track,fromMaker=false){this.audio.wake();this._makerTrack=fromMaker?copy(track):null;this.rt=this.world.buildTrack(track);this.switch=new SwitchSystem(VEHICLES[this.vehicleA],VEHICLES[this.vehicleB],this.switchDuration,this.switchCooldown);this.nitro=new NitroSystem();const mesh=this.world.makeCar(VEHICLES[this.vehicleA]);this.world.dynamicRoot.add(mesh);this.world.playerMesh=mesh;this.player=new VehicleController(mesh,this.rt,this.switch,AAA.handling);this.player.health=this.player.currentStats().max_health;this.traffic=new TrafficSystem(this.world,this.rt,VEHICLES,AAA.traffic);this.pursuit=new PursuitDirector(this.world,this.rt,VEHICLES,AAA.pursuit);this.beats=new LevelBeatDirector(this.rt);this.rhythm=new RhythmDirector(this.nitro,this.audio);this.race=new RaceDirector(this.rt,+track.laps||3);this.bots=[];for(let i=0;i<5;i++){const v=VEHICLES[(this.vehicleA+i+2)%VEHICLES.length],m=this.world.makeCar(v,null,0);this.world.dynamicRoot.add(m);const bot=new AIDriver(m,this.rt,v,5+i*8,.48+i*.09);bot.progress=5+i*8;this.bots.push(bot)}this.state='race';this.screens.show('raceHud');this.hud.show(true);this.gameTime=0;this.countdown=3.2;this.camera.pos.copy(this.player.position);$('#trackNameHud').textContent=track.name;this.screens.toast('Vertical Slice AAA · 60 FPS target')}
  pause(){if(this.state!=='race')return;this.state='pause';this.screens.show('pause')}
  resume(){if(this.state!=='pause'&&this.screens.current!=='guide')return;this.state='race';this.screens.show('raceHud')}
  toMenu(){this.state='menu';this.hud.show(false);this.screens.show('menu');this.world.showMenu(VEHICLES[this.vehicleA])}
  collisionBots(){const p=this.player,s=p.currentStats();for(const b of this.bots){if(b.takenDown>0)continue;const d=b.mesh.position.distanceTo(p.position);if(d>3.2)continue;const rel=Math.abs(p.speed-b.speed),ram=p.ramArmed>0?1+p.ramArmed*(s.ram_damage_multiplier-1):1,power=clamp(rel/25,0.12,1.4)*(s.robustness/75)*ram;const taken=b.hit(power);p.speed*=taken?.91:.965;p.impact((taken?1.5:4.5)*(1-s.resistance/180),taken?.03:.07);this.camera.impact(clamp(power,.2,1));this.audio.impact(clamp(power,.2,1));this.pursuit.aggression(.08+power*.06);if(taken){this.nitro.reward('takedown',1);this.screens.toast('TAKEDOWN + NITRO');b.mesh.rotation.z=.8;setTimeout(()=>{b.mesh.rotation.z=0},800)}}}
  trafficRewards(dt){const pf={x:Math.sin(this.player.heading),z:Math.cos(this.player.heading)};let drafting=false;for(let i=0;i<this.traffic.active;i++){const c=this.traffic.cars[i];c._near=c._near||0;c._near=Math.max(0,c._near-dt);const dx=c.mesh.position.x-this.player.position.x,dz=c.mesh.position.z-this.player.position.z,d=Math.hypot(dx,dz);if(d>3.2&&d<5.2&&c._near<=0&&Math.abs(this.player.speed)*3.6>90){c._near=2.2;this.nitro.reward('nearMiss',1);this.screens.toast('NEAR MISS',550)}if(c.direction>0&&d>4&&d<15){const front=(dx*pf.x+dz*pf.z)/(d||1),lateral=Math.abs(dx*pf.z-dz*pf.x);if(front>.72&&lateral<3.2){drafting=true;this.nitro.reward('slipstream',dt*1.8);this.player.speed+=dt*.16}}}for(const b of this.bots){const dx=b.mesh.position.x-this.player.position.x,dz=b.mesh.position.z-this.player.position.z,d=Math.hypot(dx,dz);if(d>4&&d<15){const front=(dx*pf.x+dz*pf.z)/(d||1),lateral=Math.abs(dx*pf.z-dz*pf.x);if(front>.75&&lateral<3.4){drafting=true;this.nitro.reward('slipstream',dt*2.2);this.player.speed+=dt*.18}}}if(drafting)$('#statusText').textContent='REBUFO';if(this.player.handbrake&&Math.abs(this.player.yawRate)>.25&&Math.abs(this.player.speed)*3.6>70)this.nitro.reward('drift',dt*2.2)}
  fixed(dt){if(this.countdown>0)return;this.switch.update(dt);this.nitro.update(dt);this.player.fixedUpdate(dt,this.nitro);this.world.morphCar(this.player.mesh,this.switch.a,this.switch.b,this.switch.value);this.collisionBots();resolveTrafficInteractions(this.player,this.traffic,this.nitro,this.audio)}
  update(dt){this.input.update();if(this.state==='garage'){this.world.playerMesh.rotation.y+=dt*.28;return}if(this.state!=='race')return;this.gameTime+=dt;this.countdown=Math.max(0,this.countdown-dt);$('#countdown').textContent=this.countdown>0?Math.ceil(this.countdown):'';this.player.updateInput(this.input,dt,this.nitro);this.rhythm.update(dt,this.input);const worldScale=this.player.timeActive?.42:1,simDt=dt*worldScale;this.stepper.run(simDt,s=>this.fixed(s));const intensity=this.beats.update(this.player.nearest);this.traffic.update(simDt,this.player.nearest,intensity);this.pursuit.update(simDt,this.player);for(const b of this.bots)b.update(simDt,this.player.nearest);this.race.update(simDt,this.player.nearest,this.bots);this.trafficRewards(dt);this.audio.update(Math.abs(this.player.speed)*3.6,this.player.throttle,this.nitro.mode===3?1:this.nitro.mode?0.55:0,dt);this.camera.update(dt,this.player,this.nitro.mode,this.player.timeActive);this.hud.update(this);document.body.classList.toggle('turbo',this.nitro.mode===3);document.body.classList.toggle('time-control',this.player.timeActive);if(this.race.finished){this.state='result';this.screens.show('result');$('#resultTitle').textContent=this.race.position===1?'VICTORIA':'META';$('#resultText').textContent=`${this.race.position}º · ${Math.floor(this.race.time/60)}:${(this.race.time%60).toFixed(2).padStart(5,'0')} · Heat ${Math.round(this.pursuit.heat*5)}`}}
  loop(now){const dt=Math.min(.05,(now-this.last)/1000||.016);this.last=now;try{this.update(dt);if(this.state==='menu'&&this.world.playerMesh)this.world.playerMesh.rotation.y+=dt*.16;if(this.state!=='race'&&this.state!=='pause'&&this.state!=='garage'&&this.state!=='maker'&&this.world.playerMesh)this.world.playerMesh.rotation.y+=dt*.08;this.world.render();this.input.endFrame()}catch(err){console.error(err);$('#fatal').hidden=false;$('#fatalText').textContent=String(err?.stack||err)}requestAnimationFrame(t=>this.loop(t))}
}

try{window.game=new ContraDriversGame()}catch(err){console.error(err);$('#fatal').hidden=false;$('#fatalText').textContent=String(err?.stack||err)}
