import {VEHICLES} from './game-data.js';
import {InputManager,FixedStepper,AudioEngine,clamp} from './src/core.js';
import {SwitchSystem,NitroSystem} from './src/vehicle.js';
import {RhythmDirector} from './src/directors.js';
import {OpenWorldBlueprint,OpenWorldRenderer,OpenWorldVehicle,OpenWorldTraffic,OpenWorldCamera,ActivityDirector,OpenWorldPursuit,districtAt} from './src/openworld.js';
import * as THREE from 'three';

const $=q=>document.querySelector(q), $$=q=>[...document.querySelectorAll(q)];
const fmtTime=s=>`${String(Math.floor(s/60)).padStart(2,'0')}:${String(Math.floor(s%60)).padStart(2,'0')}`;

class OpenWorldGame{
  constructor(){
    this.input=new InputManager();this.audio=new AudioEngine();this.blueprint=new OpenWorldBlueprint();this.renderer=new OpenWorldRenderer($('#gameCanvas'),this.blueprint);this.camera=new OpenWorldCamera(this.renderer.camera);this.stepper=new FixedStepper(1/120,6);this.state='menu';this.vehicleA=1;this.vehicleB=3;this.switchDuration=1;this.switchCooldown=.3;this.last=performance.now();this.waypoint=null;this.sessionTime=0;this.mapOpen=false;this.populate();this.bind();this.show('menu');this.renderer.updateChunks(new THREE.Vector3(0,0,0));this.setMenuCamera();this.loop(this.last);
  }
  setMenuCamera(){this.renderer.camera.position.set(1500,980,-1650);this.renderer.camera.lookAt(0,80,0);}
  show(id){$$('.screen').forEach(s=>s.classList.toggle('active',s.id===id));}
  toast(text,ms=1700){const t=$('#toast');t.textContent=text;t.classList.add('show');clearTimeout(this.toastTimer);this.toastTimer=setTimeout(()=>t.classList.remove('show'),ms);}
  populate(){
    for(const id of ['vehicleA','vehicleB']){const s=$(`#${id}`);VEHICLES.forEach((v,i)=>{const o=document.createElement('option');o.value=i;o.textContent=v.name;s.append(o);});}
    $('#vehicleA').value=this.vehicleA;$('#vehicleB').value=this.vehicleB;
    $('#worldStats').textContent=`64 km² · ${Math.round(this.blueprint.roadLengthKm())} km de carreteras · ${this.blueprint.activities.length} actividades`;
    this.refreshGarage();
  }
  refreshGarage(){const a=VEHICLES[this.vehicleA],b=VEHICLES[this.vehicleB];$('#garagePair').textContent=`${a.name} ↔ ${b.name}`;const rows=[['Punta',a.top_speed,b.top_speed,' km/h'],['Aceleración',a.acceleration,b.acceleration,''],['Control',a.control,b.control,''],['Resistencia',a.resistance,b.resistance,''],['Robustez',a.robustness,b.robustness,''],['Masa',a.mass,b.mass,' kg'],['Time Control',a.advanced.time_control.max_time,b.advanced.time_control.max_time,' s'],['Embestida',a.advanced.ram.max_time,b.advanced.ram.max_time,' s']];$('#garageStats').innerHTML=rows.map(r=>`<div><span>${r[0]}</span><b>${r[1]}${r[3]}</b><i>↔</i><b>${r[2]}${r[3]}</b></div>`).join('');}
  bind(){
    addEventListener('pointerdown',()=>this.audio.wake(),{once:true});addEventListener('keydown',e=>{if(e.code==='Tab')e.preventDefault();},{passive:false});
    $('#playOpenWorld').onclick=()=>this.startWorld();$('#openGarage').onclick=()=>{this.state='garage';this.show('garage');};$('#openGuide').onclick=()=>this.show('guide');
    $$('[data-back]').forEach(b=>b.onclick=()=>{if(this.player){this.state='play';this.show('hud');}else{this.state='menu';this.show('menu');this.setMenuCamera();}});
    $('#garagePlay').onclick=()=>this.startWorld();$('#vehicleA').onchange=e=>{this.vehicleA=+e.target.value;this.refreshGarage();};$('#vehicleB').onchange=e=>{this.vehicleB=+e.target.value;this.refreshGarage();};$('#switchDuration').onchange=e=>this.switchDuration=+e.target.value;$('#switchCooldown').onchange=e=>this.switchCooldown=+e.target.value;
    $('#pauseResume').onclick=()=>this.resume();$('#pauseMap').onclick=()=>this.openMap();$('#pauseMenu').onclick=()=>this.toMenu();$('#mapClose').onclick=()=>this.closeMap();
    $('#worldMap').addEventListener('pointerdown',e=>this.mapClick(e));
  }
  clearDynamic(){while(this.renderer.dynamicRoot.children.length){const o=this.renderer.dynamicRoot.children.pop();o.traverse?.(n=>{n.geometry?.dispose?.();if(n.material)(Array.isArray(n.material)?n.material:[n.material]).forEach(m=>m.dispose?.());});}}
  startWorld(){this.audio.wake();this.clearDynamic();this.switch=new SwitchSystem(VEHICLES[this.vehicleA],VEHICLES[this.vehicleB],this.switchDuration,this.switchCooldown);this.nitro=new NitroSystem();const mesh=this.renderer.makeCar(VEHICLES[this.vehicleA]);this.renderer.dynamicRoot.add(mesh);this.player=new OpenWorldVehicle(mesh,this.blueprint,this.switch,this.nitro,{ride_height:.055});this.player.health=this.player.stats().max_health;this.traffic=new OpenWorldTraffic(this.renderer,this.blueprint,VEHICLES,56);this.pursuit=new OpenWorldPursuit(this.renderer,this.blueprint,VEHICLES);this.activities=new ActivityDirector(this.blueprint);this.rhythm=new RhythmDirector(this.nitro,this.audio);this.state='play';this.mapOpen=false;this.sessionTime=0;this.show('hud');this.camera.pos.copy(this.player.position).add(new THREE.Vector3(0,6,-12));this.renderer.updateChunks(this.player.position);this.toast(`Bienvenido a Tri-City Metro · ${Math.round(this.blueprint.roadLengthKm())} km de carreteras`);}
  toMenu(){this.state='menu';this.player=null;this.show('menu');this.setMenuCamera();}
  pause(){if(this.state!=='play')return;this.state='pause';this.show('pause');}
  resume(){if(!this.player)return;this.state='play';this.show('hud');}
  openMap(){if(!this.player)return;this.state='map';this.mapOpen=true;this.show('map');this.drawWorldMap();}
  closeMap(){if(!this.player)return;this.state='play';this.mapOpen=false;this.show('hud');}
  mapClick(e){if(!this.player)return;const c=$('#worldMap'),r=c.getBoundingClientRect(),u=(e.clientX-r.left)/r.width,v=(e.clientY-r.top)/r.height,ext=this.blueprint.extent;this.waypoint=new THREE.Vector3((u*2-1)*ext,0,(v*2-1)*ext);this.drawWorldMap();this.toast('Waypoint marcado');}
  drawWorldMap(){const c=$('#worldMap'),ctx=c.getContext('2d'),w=c.width,h=c.height,ext=this.blueprint.extent,map=(x,z)=>[(x+ext)/(2*ext)*w,(z+ext)/(2*ext)*h];ctx.fillStyle='#071018';ctx.fillRect(0,0,w,h);ctx.lineCap='round';for(const road of this.blueprint.roads){ctx.strokeStyle=road.cls==='highway'?'#80bad9':road.cls==='arterial'?'#547990':'#314754';ctx.lineWidth=road.cls==='highway'?3:road.cls==='arterial'?2:1;ctx.beginPath();road.points.forEach((p,i)=>{const [x,y]=map(p.x,p.z);i?ctx.lineTo(x,y):ctx.moveTo(x,y);});ctx.stroke();}for(const a of this.blueprint.activities){if(this.activities?.completed.has(a.id))continue;const [x,y]=map(a.position.x,a.position.z);ctx.fillStyle='#ffc441';ctx.beginPath();ctx.arc(x,y,5,0,Math.PI*2);ctx.fill();}if(this.activities?.active){const [x,y]=map(this.activities.target.x,this.activities.target.z);ctx.fillStyle='#ff5c45';ctx.beginPath();ctx.arc(x,y,8,0,Math.PI*2);ctx.fill();}if(this.waypoint){const [x,y]=map(this.waypoint.x,this.waypoint.z);ctx.strokeStyle='#20d7ff';ctx.lineWidth=3;ctx.beginPath();ctx.arc(x,y,9,0,Math.PI*2);ctx.stroke();}if(this.player){const [x,y]=map(this.player.position.x,this.player.position.z);ctx.fillStyle='#44f2ff';ctx.beginPath();ctx.arc(x,y,7,0,Math.PI*2);ctx.fill();}}
  drawMiniMap(){const c=$('#minimap'),ctx=c.getContext('2d'),w=c.width,h=c.height,p=this.player,range=650;ctx.clearRect(0,0,w,h);ctx.fillStyle='rgba(5,14,22,.68)';ctx.fillRect(0,0,w,h);const map=(x,z)=>[w/2+(x-p.position.x)/range*w/2,h/2+(z-p.position.z)/range*h/2];for(const road of this.blueprint.roads){let visible=false;for(const q of road.points)if(Math.abs(q.x-p.position.x)<range&&Math.abs(q.z-p.position.z)<range){visible=true;break;}if(!visible)continue;ctx.strokeStyle=road.cls==='highway'?'rgba(170,220,240,.7)':'rgba(110,145,160,.45)';ctx.lineWidth=road.cls==='highway'?2:1;ctx.beginPath();road.points.forEach((q,i)=>{const [x,y]=map(q.x,q.z);i?ctx.lineTo(x,y):ctx.moveTo(x,y);});ctx.stroke();}ctx.save();ctx.translate(w/2,h/2);ctx.rotate(-p.heading);ctx.fillStyle='#28e6ff';ctx.beginPath();ctx.moveTo(0,-8);ctx.lineTo(5,7);ctx.lineTo(-5,7);ctx.closePath();ctx.fill();ctx.restore();const target=this.activities?.active?this.activities.target:this.waypoint;if(target){const dx=target.x-p.position.x,dz=target.z-p.position.z,d=Math.hypot(dx,dz),s=Math.min(1,(w*.42)/(d/range*w/2||1)),[tx,ty]=map(p.position.x+dx*s,p.position.z+dz*s);ctx.fillStyle='#ffd342';ctx.beginPath();ctx.arc(tx,ty,5,0,Math.PI*2);ctx.fill();}}
  updateHud(){const p=this.player,s=p.stats(),d=districtAt(p.position.x,p.position.z),near=this.activities.nearest(p.position),target=this.activities.active?this.activities.target:this.waypoint;$('#speed').textContent=String(Math.round(Math.abs(p.speed)*3.6)).padStart(3,'0');$('#district').textContent=d.name;$('#score').textContent=p.score.toLocaleString('es-ES');$('#heat').style.width=`${this.pursuit.heat*100}%`;$('#health').style.width=`${clamp(p.health/s.max_health*100,0,100)}%`;$('#timeBar').style.width=`${p.timeReserve*100}%`;$('#ramBar').style.width=`${p.ramCharge*100}%`;$('#n1').style.width=`${this.nitro.n1*100}%`;$('#n2').style.width=`${this.nitro.n2*100}%`;$('#n3').style.width=`${this.nitro.n3*100}%`;$('#switchText').textContent=`${this.switch.a.name} ${Math.round((1-this.switch.value)*100)}% ↔ ${Math.round(this.switch.value*100)}% ${this.switch.b.name}`;$('#worldClock').textContent=fmtTime(this.sessionTime);let mission='Explora libremente';if(this.activities.active){const dist=p.position.distanceTo(this.activities.target);mission=`${this.activities.active.name} · ${Math.round(dist)} m · ${Math.max(0,Math.ceil(this.activities.limit-this.activities.time))} s`;}else if(near&&near.distance<75)mission=`F · ${near.activity.name}`;else if(target)mission=`Waypoint · ${Math.round(p.position.distanceTo(target))} m`;$('#missionText').textContent=mission;$('#status').textContent=[this.nitro.mode===3?'TURBO':this.nitro.mode===2?'REMIX':this.nitro.mode===1?'NITRO':'',p.timeActive?'TIME CONTROL':'',this.pursuit.heat>.45?'PURSUIT':''].filter(Boolean).join(' · ');this.renderRhythm();this.drawMiniMap();}
  renderRhythm(){const root=$('#rhythmLanes');root.innerHTML='';for(const n of this.rhythm.upcoming(8)){const i=document.createElement('i');i.className=`note lane${n.lane}`;i.style.bottom=`${clamp(10+n.delta*34,8,94)}%`;root.append(i);}$('#rhythmJudge').textContent=this.rhythm.judge;}
  fixed(dt){this.switch.update(dt);this.nitro.update(dt);this.player.update(dt);this.renderer.morphCar(this.player.mesh,this.switch.a,this.switch.b,this.switch.value);this.traffic.interactions(this.player,this.nitro,this.audio);}
  playUpdate(dt){this.sessionTime+=dt;this.input.update();if(this.input.pressed.has('Escape')){this.pause();return;}if(this.input.pressed.has('Tab')){this.openMap();return;}if(this.input.pressed.has('KeyH')){this.state='guide';this.show('guide');return;}if(this.input.pressed.has('KeyC'))this.camera.cycle();if(this.input.pressed.has('KeyR'))this.player.spawn(this.player.position.x,this.player.position.z);if(this.input.pressed.has('KeyF')&&!this.activities.active){const n=this.activities.nearest(this.player.position);if(n&&n.distance<80){this.activities.start(n.activity,this.player);this.waypoint=null;this.toast(`ACTIVIDAD: ${n.activity.name}`);}}
    this.player.input(this.input,dt);this.rhythm.update(dt,this.input);const worldScale=this.player.timeActive?.42:1,simDt=dt*worldScale;this.stepper.run(simDt,s=>this.fixed(s));this.traffic.update(simDt,this.player);this.pursuit.update(simDt,this.player);if(this.player.lastImpact>.35)this.pursuit.aggression(.0025);if(this.player.ramArmed>.35)this.pursuit.aggression(.0009);const result=this.activities.update(simDt,this.player);if(result)this.toast(result.success?`${result.name} +${result.reward}`:`${result.name}: tiempo agotado`,2600);if(this.player.health<=0){this.toast('VEHÍCULO DESTRUIDO · reapareciendo',2200);this.player.health=this.player.stats().max_health;this.player.spawn(0,-650);this.pursuit.heat=.2;}this.renderer.updateChunks(this.player.position);this.camera.update(dt,this.player,this.nitro);this.audio.update(Math.abs(this.player.speed)*3.6,this.player.throttle,this.nitro.mode===3?1:this.nitro.mode?0.5:0,dt);this.updateHud();}
  loop(now){const dt=Math.min(.05,(now-this.last)/1000||.016);this.last=now;try{if(this.state==='play')this.playUpdate(dt);else if(this.state==='map')this.input.update();else if(this.state==='guide'&&this.player&&this.input.pressed.has('Escape')){this.state='play';this.show('hud');}if(this.state==='menu'){const t=now*.00008,r=1900;this.renderer.camera.position.set(Math.cos(t)*r,950,Math.sin(t)*r);this.renderer.camera.lookAt(0,50,0);}this.renderer.render();this.input.endFrame();}catch(err){console.error(err);$('#fatal').hidden=false;$('#fatalText').textContent=String(err?.stack||err);}requestAnimationFrame(t=>this.loop(t));}
}

try{window.game=new OpenWorldGame();}catch(err){console.error(err);$('#fatal').hidden=false;$('#fatalText').textContent=String(err?.stack||err);}
