import fs from 'node:fs';
import path from 'node:path';
const root=process.cwd(),read=p=>fs.readFileSync(path.join(root,p),'utf8'),fail=m=>{console.error('FAIL:',m);process.exitCode=1},ok=m=>console.log('OK:',m);
const html=read('index.html'),app=read('openworld-app.js'),world=read('src/openworld.js'),up=read('src/openworld-upgrades.js'),boot=read('openworld-bootstrap.js');
const ids=[...html.matchAll(/id="([^"]+)"/g)].map(m=>m[1]),dup=ids.filter((x,i)=>ids.indexOf(x)!==i);dup.length?fail('IDs duplicados: '+[...new Set(dup)]):ok('HTML IDs únicos');
const required=['gameCanvas','menu','garage','guide','hud','speed','district','score','heat','health','minimap','rhythmLanes','pause','map','worldMap','fatal'];const missing=required.filter(id=>!ids.includes(id));missing.length?fail('IDs críticos ausentes: '+missing.join(', ')):ok('HUD y pantallas open-world presentes');
for(const f of ['game-data.js','styles.css','openworld-app.js','openworld-bootstrap.js','src/openworld.js','src/openworld-upgrades.js','src/core.js','src/vehicle.js','src/directors.js'])if(!fs.existsSync(path.join(root,f)))fail('Falta '+f);if(!process.exitCode)ok('Módulos open-world presentes');
if(!html.includes('v0.8.1')||!html.includes('openworld-bootstrap.js'))fail('index no carga v0.8.1/bootstrap');else ok('v0.8.1 bootstrap activo');
for(const token of ['extent=4000','I-85-ring','mountain-bypass','OpenWorldTraffic','OpenWorldPursuit','ActivityDirector'])if(!world.includes(token))fail('Falta contrato world: '+token);if(!process.exitCode)ok('Contratos de mundo abierto presentes');
for(const token of ['new OpenWorldBlueprint()','new OpenWorldVehicle','new OpenWorldTraffic','new OpenWorldPursuit','drawWorldMap','KeyF'])if(!app.includes(token))fail('Falta contrato app: '+token);if(!process.exitCode)ok('Contratos gameplay presentes');
for(const token of ['CAR_DESIGNS','this.steer=expSmoothing(this.steer,-input.axes.steer','time-control-world','ramBurstTimer','policeMax:14','showGaragePair'])if(!up.includes(token))fail('Falta upgrade: '+token);if(!process.exitCode)ok('Controles, autos, Time Control, RAM, garaje y policía cubiertos');
if(!boot.includes('openworld-upgrades.js')||!boot.includes('openworld-app.js'))fail('Bootstrap incompleto');else ok('Bootstrap ordena upgrades antes del juego');
if(process.exitCode)process.exit(process.exitCode);console.log('ContraDrivers Open World v0.8.1 static QA: PASS');
