import {copy,clamp} from './core.js';

export class TrackMaker{
  constructor(canvas,onPlay){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.onPlay=onPlay;this.tool='select';this.zoom=1.8;this.pan={x:canvas.width/2,y:canvas.height/2};this.drag=null;this.selected=-1;this.history=[];this.future=[];this.doc=this.defaultDoc();this.resize();addEventListener('resize',()=>this.resize());this.bind();this.renderLoop()}
  defaultDoc(){return{id:'maker_'+Date.now(),name:'Maker Circuit',width:14,laps:3,environment:{terrain_color:'#31453a',sky_color:'#739ab1',fog_near:80,fog_far:400,accent:'#18c7ff'},route_smoothing:{samples_per_segment:6,tension:.58},waypoints:[[0,0,0],[0,0,55],[35,3,85],[85,6,75],[110,2,30],[90,0,-20],[35,0,-45],[-20,0,-30],[-40,1,12]],checkpoint_indices:[0,2,4,6],surfaces:[{name:'asphalt',from:0,to:8,grip:1,color:'#383b3f'}],tunnel_segments:[],ramps:[],alternate_roads:[],scenery_zones:[{type:'downtown',center:[45,0,25],scale:.8}],road_profiles:[{from:0,to:8,class:'avenue',width:14,lanes:2}],aaa_profile:{theme:'MAKER DISTRICT',districts:['custom'],traffic:.55,police:.5,aggression:.5,stunt:.5,palette:['#18c7ff','#ffb65a','#111a22'],signature:'custom'}}}
  resize(){const r=this.canvas.getBoundingClientRect();this.canvas.width=Math.max(1,Math.floor(r.width*devicePixelRatio));this.canvas.height=Math.max(1,Math.floor(r.height*devicePixelRatio));this.pan.x=this.canvas.width*.5;this.pan.y=this.canvas.height*.5}
  bind(){
    this.canvas.addEventListener('wheel',e=>{e.preventDefault();const old=this.zoom;this.zoom=clamp(this.zoom*Math.exp(-e.deltaY*.001),.35,8);const p=this.pointer(e);this.pan.x=p.x-(p.x-this.pan.x)*(this.zoom/old);this.pan.y=p.y-(p.y-this.pan.y)*(this.zoom/old)},{passive:false});
    this.canvas.addEventListener('pointerdown',e=>{const p=this.pointer(e);if(e.button===1){this.drag={kind:'pan',x:p.x,y:p.y,px:this.pan.x,py:this.pan.y};return}const w=this.screenToWorld(p),hit=this.hitNode(w);if(this.tool==='select'){if(hit>=0){this.pushHistory();this.selected=hit;this.drag={kind:'node',index:hit}}}else if(this.tool==='draw'){this.pushHistory();if(hit>=0){const base=this.doc.waypoints[hit];this.doc.waypoints.splice(hit+1,0,[w.x,base[1],w.z]);this.reindexAfterInsert(hit+1);this.selected=hit+1}else{this.doc.waypoints.push([w.x,+document.querySelector('#makerElevation')?.value||0,w.z]);this.selected=this.doc.waypoints.length-1}}else if(this.tool==='checkpoint'){if(hit>=0){this.pushHistory();const a=this.doc.checkpoint_indices,i=a.indexOf(hit);i>=0?a.splice(i,1):a.push(hit);if(!a.includes(0))a.push(0);a.sort((a,b)=>a-b)}}else if(this.tool==='ramp'){this.pushHistory();this.doc.ramps.push({id:'r'+Date.now(),type:'normal',position:[w.x,+document.querySelector('#makerElevation')?.value||0,w.z],rotation_y:0,scale:[5.5,.6,8]})}else if(this.tool==='tunnel'){if(hit>=0){this.pushHistory();const a=this.doc.tunnel_segments,i=a.indexOf(hit);i>=0?a.splice(i,1):a.push(hit)}}else if(this.tool==='delete'){if(hit>0&&this.doc.waypoints.length>5){this.pushHistory();this.doc.waypoints.splice(hit,1);this.reindexAfterDelete(hit);this.selected=-1}}});
    this.canvas.addEventListener('pointermove',e=>{if(!this.drag)return;const p=this.pointer(e);if(this.drag.kind==='pan'){this.pan.x=this.drag.px+(p.x-this.drag.x);this.pan.y=this.drag.py+(p.y-this.drag.y)}else if(this.drag.kind==='node'){const w=this.screenToWorld(p),y=this.doc.waypoints[this.drag.index][1];this.doc.waypoints[this.drag.index]=[w.x,y,w.z]}});
    addEventListener('pointerup',()=>this.drag=null);
    addEventListener('keydown',e=>{if(!document.querySelector('#maker')?.classList.contains('active'))return;if(e.ctrlKey&&e.code==='KeyZ'){e.preventDefault();this.undo()}if(e.ctrlKey&&e.code==='KeyY'){e.preventDefault();this.redo()}if(e.code==='Delete'&&this.selected>0){this.tool='delete';this.deleteSelected()}const tools={Digit1:'select',Digit2:'draw',Digit3:'checkpoint',Digit4:'ramp',Digit5:'tunnel',Digit6:'delete'};if(tools[e.code])this.setTool(tools[e.code])});
  }
  pointer(e){const r=this.canvas.getBoundingClientRect(),sx=this.canvas.width/r.width,sy=this.canvas.height/r.height;return{x:(e.clientX-r.left)*sx,y:(e.clientY-r.top)*sy}}
  worldToScreen(p){return{x:this.pan.x+p[0]*this.zoom,y:this.pan.y+p[2]*this.zoom}}
  screenToWorld(p){return{x:(p.x-this.pan.x)/this.zoom,z:(p.y-this.pan.y)/this.zoom}}
  hitNode(w){let best=-1,d=11/this.zoom;this.doc.waypoints.forEach((p,i)=>{const q=Math.hypot(p[0]-w.x,p[2]-w.z);if(q<d){d=q;best=i}});return best}
  pushHistory(){this.history.push(copy(this.doc));if(this.history.length>100)this.history.shift();this.future.length=0}
  undo(){if(!this.history.length)return;this.future.push(copy(this.doc));this.doc=this.history.pop();this.selected=-1;this.status('Undo')}
  redo(){if(!this.future.length)return;this.history.push(copy(this.doc));this.doc=this.future.pop();this.selected=-1;this.status('Redo')}
  setTool(t){this.tool=t;document.querySelectorAll('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===t));this.status(t.toUpperCase())}
  deleteSelected(){if(this.selected<=0)return;this.pushHistory();const i=this.selected;this.doc.waypoints.splice(i,1);this.reindexAfterDelete(i);this.selected=-1}
  reindexAfterInsert(i){this.doc.checkpoint_indices=this.doc.checkpoint_indices.map(x=>x>=i?x+1:x);this.doc.tunnel_segments=this.doc.tunnel_segments.map(x=>x>=i?x+1:x);for(const p of this.doc.road_profiles||[]){if(p.from>=i)p.from++;if(p.to>=i)p.to++}for(const s of this.doc.surfaces||[]){if(s.from>=i)s.from++;if(s.to>=i)s.to++}}
  reindexAfterDelete(i){const remap=a=>a.filter(x=>x!==i).map(x=>x>i?x-1:x);this.doc.checkpoint_indices=remap(this.doc.checkpoint_indices);if(!this.doc.checkpoint_indices.includes(0))this.doc.checkpoint_indices.unshift(0);this.doc.tunnel_segments=remap(this.doc.tunnel_segments);for(const p of this.doc.road_profiles||[]){if(p.from>i)p.from--;if(p.to>i)p.to--}for(const s of this.doc.surfaces||[]){if(s.from>i)s.from--;if(s.to>i)s.to--}}
  status(t){const e=document.querySelector('#makerStatus');if(e)e.textContent=t}
  save(){localStorage.setItem('contradrivers:maker:v070',JSON.stringify(this.doc));this.status('Guardado local')}
  load(){try{const d=JSON.parse(localStorage.getItem('contradrivers:maker:v070'));if(d?.waypoints?.length>=5){this.pushHistory();this.doc=d;this.status('Pista cargada')}}catch{this.status('No se pudo cargar')}}
  export(){const blob=new Blob([JSON.stringify(this.doc,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(this.doc.name||'track')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
  validate(){const errors=[];if(this.doc.waypoints.length<5)errors.push('Se necesitan al menos 5 nodos');if(!this.doc.checkpoint_indices.includes(0))errors.push('Salida/meta debe ser checkpoint');return errors}
  play(){const e=this.validate();if(e.length){this.status(e[0]);return}this.onPlay?.(copy(this.doc))}
  renderLoop(){this.draw();requestAnimationFrame(()=>this.renderLoop())}
  draw(){const c=this.ctx,w=this.canvas.width,h=this.canvas.height;c.fillStyle='#071019';c.fillRect(0,0,w,h);c.save();c.strokeStyle='rgba(80,130,160,.12)';c.lineWidth=1;const grid=20*this.zoom;for(let x=((this.pan.x%grid)+grid)%grid;x<w;x+=grid){c.beginPath();c.moveTo(x,0);c.lineTo(x,h);c.stroke()}for(let y=((this.pan.y%grid)+grid)%grid;y<h;y+=grid){c.beginPath();c.moveTo(0,y);c.lineTo(w,y);c.stroke()}const pts=this.doc.waypoints.map(p=>this.worldToScreen(p));if(pts.length>1){c.strokeStyle='#394a55';c.lineWidth=(+this.doc.width||14)*this.zoom;c.lineJoin='round';c.beginPath();pts.forEach((p,i)=>i?c.lineTo(p.x,p.y):c.moveTo(p.x,p.y));c.closePath();c.stroke();c.strokeStyle='#d7e6eb';c.lineWidth=Math.max(1,this.zoom*.5);c.setLineDash([8*this.zoom,8*this.zoom]);c.stroke();c.setLineDash([])}pts.forEach((p,i)=>{c.beginPath();c.arc(p.x,p.y,(i===this.selected?7:5)*devicePixelRatio,0,Math.PI*2);c.fillStyle=this.doc.checkpoint_indices.includes(i)?'#ffd45a':this.doc.tunnel_segments.includes(i)?'#9a70ff':'#18c7ff';c.fill();if(i===0){c.strokeStyle='#fff';c.lineWidth=2;c.stroke()}});for(const r of this.doc.ramps||[]){const p=this.worldToScreen(r.position);c.fillStyle='#ff7c3c';c.fillRect(p.x-7,p.y-4,14,8)}c.restore()}
}
