import * as THREE from 'three';
import {clamp,lerp,expSmoothing} from './core.js';
import {OpenWorldRenderer,OpenWorldVehicle,OpenWorldTraffic,terrainHeight} from './openworld.js';
import {createDetailedCar,morphDetailedCar,disposeObject3D} from './vehicle-factory.js';
import {settings} from './settings.js';

const forward=yaw=>new THREE.Vector3(Math.sin(yaw),0,Math.cos(yaw));
const angleDelta=(a,b)=>Math.atan2(Math.sin(b-a),Math.cos(b-a));
function distanceAlongRoad(road,position){let bestD=Infinity,best=0;for(let i=1;i<road.points.length;i++){const a=road.points[i-1],b=road.points[i],vx=b.x-a.x,vz=b.z-a.z,wx=position.x-a.x,wz=position.z-a.z,l2=vx*vx+vz*vz||1,t=clamp((wx*vx+wz*vz)/l2,0,1),x=a.x+vx*t,z=a.z+vz*t,d=(x-position.x)**2+(z-position.z)**2;if(d<bestD){bestD=d;best=road.cum[i-1]+Math.sqrt(l2)*t}}return best}

export class GameRenderer extends OpenWorldRenderer{
  constructor(canvas,blueprint){super(canvas,blueprint);this.showroomRoot=null;this._worldLook=null;this._garageSpin=0}
  makeCar(v,color=v.color,detail=1){return createDetailedCar(v,color,detail)}
  morphCar(mesh,a,b,t){morphDetailedCar(mesh,a,b,t)}
  disposeDynamic(){while(this.dynamicRoot.children.length){const o=this.dynamicRoot.children[0];this.dynamicRoot.remove(o);disposeObject3D(o)}}
  ensureShowroom(){if(this.showroomRoot)return;const g=this.showroomRoot=new THREE.Group();g.visible=false;this.root.add(g);const floor=new THREE.Mesh(new THREE.CircleGeometry(8,64),new THREE.MeshPhysicalMaterial({color:0x11171d,metalness:.7,roughness:.24,clearcoat:.72}));floor.rotation.x=-Math.PI/2;g.add(floor);const ring=new THREE.Mesh(new THREE.TorusGeometry(5.7,.045,8,96),new THREE.MeshBasicMaterial({color:0x22cfff,toneMapped:false}));ring.rotation.x=Math.PI/2;ring.position.y=.025;g.add(ring);for(let i=0;i<6;i++){const p=new THREE.PointLight(i%2?0x438dff:0xffffff,1.7,13,2);p.position.set(Math.cos(i/6*Math.PI*2)*6,2.6,Math.sin(i/6*Math.PI*2)*6);g.add(p)}}
  showGaragePair(a,b){this.ensureShowroom();if(!this._worldLook)this._worldLook={bg:this.scene.background.clone(),fog:this.scene.fog.color.clone()};this.scene.background.set(0x07090d);this.scene.fog.color.set(0x07090d);this.staticRoot.visible=false;this.chunkRoot.visible=false;this.dynamicRoot.visible=false;this.showroomRoot.visible=true;const old=this.showroomRoot.getObjectByName('cars');if(old){this.showroomRoot.remove(old);disposeObject3D(old)}const cars=new THREE.Group();cars.name='cars';const ca=this.makeCar(a,a.color,1),cb=this.makeCar(b,b.color,1);ca.position.set(-2.2,.06,.2);ca.rotation.y=.34;cb.position.set(2.5,.06,1.1);cb.rotation.y=-.28;cb.scale.multiplyScalar(.84);cars.add(ca,cb);this.showroomRoot.add(cars);this.camera.position.set(-8.8,3.2,-10.1);this.camera.lookAt(-.35,.85,.2);this._garageSpin=0}
  updateShowroom(dt){if(!this.showroomRoot?.visible)return;const cars=this.showroomRoot.getObjectByName('cars');if(cars){this._garageSpin+=dt*.26;cars.rotation.y=this._garageSpin}}
  hideGarage(){if(!this.showroomRoot?.visible)return;this.showroomRoot.visible=false;this.staticRoot.visible=true;this.chunkRoot.visible=true;this.dynamicRoot.visible=true;if(this._worldLook){this.scene.background.copy(this._worldLook.bg);this.scene.fog.color.copy(this._worldLook.fog);this._worldLook=null}}
}

export class PlayerVehicle extends OpenWorldVehicle{
  constructor(mesh,blueprint,switchSystem,nitro,config={}){super(mesh,blueprint,switchSystem,nitro,config);this.ramImpulse=0;this.ramPower=0}
  input(input,realDt){
    // InputManager already maps A/left to -1 and D/right to +1. Positive yaw turns right in this runtime.
    this.steer=expSmoothing(this.steer,input.axes.steer,9,realDt);
    this.throttle=input.axes.throttle;this.brake=input.axes.brake;this.handbrake=input.down('handbrake');
    if(input.pressedAction('switch'))this.switch.request();if(input.pressedAction('nitro'))this.nitro.base();if(input.pressedAction('remix'))this.nitro.remix();this.timeActive=input.down('time')&&this.timeReserve>.005;
    const s=this.stats();if(input.down('ram')&&this.ramImpulse<=0)this.ramCharge=clamp(this.ramCharge+realDt/Math.max(.1,s.ram_max_time),0,1);if((input.releasedAction('ram')||this.ramCharge>=1)&&this.ramCharge>.03){this.ramPower=this.ramCharge;this.ramImpulse=.22+.16*this.ramPower;this.ramArmed=.32+.68*this.ramPower;this.speed+=3+8*this.ramPower;this.ramCharge=0}
  }
  update(simDt,realDt=simDt){
    const s=this.stats(),[ns,na]=this.nitro.multipliers(s),max=(s.top_speed*ns)/3.6,kmh=Math.abs(this.speed)*3.6,tc=this.timeActive?s.time_control_control_multiplier:1;
    if(this.timeActive)this.timeReserve=Math.max(0,this.timeReserve-realDt/Math.max(.5,s.time_control_max));else this.timeReserve=Math.min(1,this.timeReserve+realDt*.08);if(this.timeReserve<=0)this.timeActive=false;
    const ramActive=this.ramImpulse>0,ramAccel=ramActive?lerp(1,s.ram_acceleration_multiplier,Math.max(.35,this.ramPower)):1,ramSpeed=ramActive?lerp(1,s.ram_top_speed_multiplier,this.ramPower):1,target=max*ramSpeed,acc=(3.8+s.acceleration*.09)*na*ramAccel*(1-Math.pow(clamp(Math.abs(this.speed)/Math.max(1,target),0,1),1.65));if(this.throttle)this.speed+=acc*this.throttle*simDt;if(ramActive)this.speed+=(7+18*this.ramPower)*simDt;if(this.brake){const force=(5+s.braking*.11)*this.brake;this.speed-=Math.sign(this.speed||1)*force*simDt;if(Math.abs(this.speed)<.25)this.speed=-this.brake*2}
    const drag=.22+.0022*kmh+.000012*kmh*kmh;this.speed-=Math.sign(this.speed)*Math.min(Math.abs(this.speed),drag*simDt);this.speed=clamp(this.speed,-9,target*1.04);
    const n=clamp(Math.abs(this.speed)/Math.max(1,max),0,1),steerAvail=lerp(1,s.high_speed_steer,Math.pow(n,1.4)),steerAngle=this.steer*(Math.PI/180)*30*steerAvail*tc,near=this.blueprint.nearestRoad(this.position.x,this.position.z),onRoad=near&&near.distance<near.width*.62,grip=(s.grip||.85)*(onRoad?1:.42)*(this.handbrake?.36:1),wheelbase=2.4+s.mass/5500,desired=Math.tan(steerAngle)*this.speed/wheelbase*(.7+s.control/135);this.yawRate=expSmoothing(this.yawRate,desired,(2.8+s.steer_response*4.2)*grip,simDt);if(this.handbrake&&kmh>65)this.yawRate*=1.25+Math.abs(this.steer)*.7;const slip=-this.yawRate*this.speed*.18*(1-grip*.38);this.lateral=expSmoothing(this.lateral,slip,(2+grip*6)*(this.handbrake?.48:1),simDt);this.heading+=this.yawRate*simDt;
    const f=forward(this.heading),r=new THREE.Vector3(f.z,0,-f.x);this.position.addScaledVector(f,this.speed*simDt).addScaledVector(r,this.lateral*simDt);const ext=this.blueprint.extent-20;if(Math.abs(this.position.x)>ext||Math.abs(this.position.z)>ext){this.position.x=clamp(this.position.x,-ext,ext);this.position.z=clamp(this.position.z,-ext,ext);this.speed*=.35}
    const nr=this.blueprint.nearestRoad(this.position.x,this.position.z),terrain=terrainHeight(this.position.x,this.position.z);let targetY=terrain+.055,targetPitch=0;if(nr&&nr.distance<nr.width*.72){targetY=nr.point.y+.055;targetPitch=Math.atan2(nr.tangent.y,Math.hypot(nr.tangent.x,nr.tangent.z))}else this.speed*=1-simDt*.42;this.position.y=expSmoothing(this.position.y,targetY,18,simDt);this.pitch=expSmoothing(this.pitch,targetPitch,10,simDt);this.ramImpulse=Math.max(0,this.ramImpulse-realDt);this.ramArmed=Math.max(0,this.ramArmed-realDt*1.7);this.lastImpact=Math.max(0,this.lastImpact-realDt);this.mesh.userData.ramVisualZ=ramActive?1+.055*this.ramPower:1;this.sync()
  }
}

export class TrafficSystem extends OpenWorldTraffic{
  constructor(renderer,blueprint,vehicles,count=52){super(renderer,blueprint,vehicles,count);for(const c of this.cars)c.contactLock=0}
  respawn(c,player){const road=this.blueprint.randomRoadNear(player.position.x,player.position.z,this.rng,1400);c.road=road;const base=distanceAlongRoad(road,player.position),offset=(160+this.rng()*1000)*(this.rng()<.5?-1:1);c.d=road.loop?(base+offset+road.length)%road.length:clamp(base+offset,0,road.length);c.speed=12+this.rng()*20;c.dir=this.rng()<.14?-1:1;c.lane=this.rng()<.5?-.28:.28;c.contactLock=.6}
  update(dt,player){super.update(dt,player);for(const c of this.cars)c.contactLock=Math.max(0,(c.contactLock||0)-dt)}
  interactions(player,nitro,audio){const s=player.stats(),pf=forward(player.heading);for(const c of this.cars){const d=c.mesh.position.distanceTo(player.position);if(d>5.5)continue;const cf=forward(c.mesh.rotation.y),sameDirection=pf.dot(cf)>.35,to=c.mesh.position.clone().sub(player.position).setY(0),len=to.length();if(len>.001)to.multiplyScalar(1/len);const front=pf.dot(to),relative=Math.abs(player.speed-c.speed*(sameDirection?1:-1));if(d>2.8&&d<5.2&&c.nearLock<=0&&Math.abs(player.speed)*3.6>95){c.nearLock=2;nitro.reward('nearMiss',1);player.score+=60;continue}if(d>2.7||c.contactLock>0)continue;c.contactLock=.42;if(player.ramArmed>.08&&front>.05){const power=clamp(player.ramArmed,0,1);c.speed+=8+18*power;c.lane+=Math.sign(to.x||1)*(.18+.28*power);nitro.reward('trafficCheck',1+power);player.score+=Math.round(180+320*power);audio?.impact(.45+.4*power);player.ramArmed*=.42;continue}if(sameDirection&&front>.1&&s.mass>c.mass*.55){const force=clamp((s.mass/c.mass)*relative/22,.12,1);c.speed+=force*5;player.speed*=1-.035*(1-force);nitro.reward('trafficCheck',.5+force);player.score+=Math.round(90+force*160);audio?.impact(.25+force*.3)}else{const dmg=(sameDirection?5:18)*(1+c.mass/2500)*clamp(relative/26,.4,1.7)*(1-s.resistance/190);player.health=Math.max(0,player.health-dmg);player.speed*=sameDirection?.9:.68;player.lastImpact=.5;audio?.impact(clamp(dmg/28,.2,1))}}}
}

export class ChaseCamera{
  constructor(camera){this.camera=camera;this.pos=new THREE.Vector3();this.look=new THREE.Vector3();this.fov=66;this.mode=0}
  cycle(){this.mode=(this.mode+1)%3}
  update(dt,p,nitro){const kmh=Math.abs(p.speed)*3.6,n=clamp(kmh/400,0,1),f=forward(p.heading),r=new THREE.Vector3(f.z,0,-f.x),charge=p.ramCharge||0,release=p.ramImpulse>0?clamp(p.ramImpulse/.38,0,1):0;let target,look;if(this.mode===2){target=p.position.clone().add(new THREE.Vector3(0,1.2,0)).addScaledVector(f,.35);look=p.position.clone().add(new THREE.Vector3(0,.8,0)).addScaledVector(f,30)}else if(this.mode===1){target=p.position.clone().addScaledVector(f,-8.5-charge*2.2+release*1.6).add(new THREE.Vector3(0,4.2,0));look=p.position.clone().add(new THREE.Vector3(0,.7,0)).addScaledVector(f,11)}else{target=p.position.clone().addScaledVector(f,-12-n*4.5-charge*4.2+release*2.4).add(new THREE.Vector3(0,5.2+n*1.4,0)).addScaledVector(r,-p.steer*.55);look=p.position.clone().add(new THREE.Vector3(0,.75,0)).addScaledVector(f,10+n*12+release*4)}this.pos.lerp(target,1-Math.exp(-7*dt));this.look.lerp(look,1-Math.exp(-8*dt));this.camera.position.copy(this.pos);this.camera.lookAt(this.look);this.fov=expSmoothing(this.fov,66+n*15+(nitro.mode===3?6:nitro.mode?2:0)+charge*3+release*5,4.5,dt);this.camera.fov=this.fov;this.camera.updateProjectionMatrix()}
}

export class PoliceSystem{
  constructor(renderer,blueprint,vehicles){this.renderer=renderer;this.blueprint=blueprint;this.heat=0;this.units=[];for(let i=0;i<14;i++){const mesh=renderer.makeCar(vehicles[(i+4)%vehicles.length],i%2?0x16315f:0xe7e9ec,0);mesh.visible=false;const red=new THREE.PointLight(0xff2038,.9,7),blue=new THREE.PointLight(0x246cff,.9,7);red.position.set(-.45,1.05,0);blue.position.set(.45,1.05,0);mesh.add(red,blue);renderer.dynamicRoot.add(mesh);this.units.push({mesh,position:new THREE.Vector3(),heading:0,speed:0,active:false,cool:0,stun:0,red,blue})}}
  aggression(amount){if(settings.get('policeEnabled'))this.heat=clamp(this.heat+amount,0,1)}
  setEnabled(enabled){settings.set('policeEnabled',enabled);if(!enabled)this.disableAll()}
  disableAll(){this.heat=0;for(const u of this.units){u.active=false;u.mesh.visible=false}}
  activeCount(){return this.units.reduce((n,u)=>n+(u.active?1:0),0)}
  spawn(u,player,i){const f=forward(player.heading),side=new THREE.Vector3(f.z,0,-f.x);u.position.copy(player.position).addScaledVector(f,-140-i*18).addScaledVector(side,(i%2?1:-1)*(24+(i%4)*8));const road=this.blueprint.nearestRoad(u.position.x,u.position.z);if(road){u.position.copy(road.point);u.heading=Math.atan2(road.tangent.x,road.tangent.z)}else u.heading=player.heading;u.position.y+=.055;u.speed=Math.max(23,Math.abs(player.speed)*.82);u.active=true;u.mesh.visible=true;u.cool=1.1;u.stun=0}
  update(dt,player){if(!settings.get('policeEnabled')){if(this.activeCount()||this.heat)this.disableAll();return}const kmh=Math.abs(player.speed)*3.6;this.heat=clamp(this.heat+(kmh>170?(kmh-170)/520*.04*dt:-.012*dt),0,1);const max=settings.get('policeMax'),wanted=Math.min(max,kmh>55?Math.max(2,Math.ceil(this.heat*Math.max(2,max))):0);for(let i=0;i<this.units.length;i++){const u=this.units[i];if(i<wanted&&!u.active)this.spawn(u,player,i);if(i>=wanted&&u.active){u.active=false;u.mesh.visible=false;continue}if(!u.active)continue;u.cool=Math.max(0,u.cool-dt);u.stun=Math.max(0,u.stun-dt);u.red.visible=Math.floor(performance.now()/160+i)%2===0;u.blue.visible=!u.red.visible;if(u.stun>0){u.speed*=1-dt*2.5;continue}const pf=forward(player.heading),predict=player.position.clone().addScaledVector(pf,18+Math.abs(player.speed)*(.32+i*.008)),target=Math.atan2(predict.x-u.position.x,predict.z-u.position.z),delta=angleDelta(u.heading,target);u.heading+=clamp(delta,-(1+.28*this.heat)*dt,(1+.28*this.heat)*dt);u.speed=lerp(u.speed,Math.max(27,Math.abs(player.speed)*(1.03+.16*this.heat)),1-Math.exp(-.9*dt));u.position.x+=Math.sin(u.heading)*u.speed*dt;u.position.z+=Math.cos(u.heading)*u.speed*dt;const road=this.blueprint.nearestRoad(u.position.x,u.position.z);if(road&&road.distance<road.width*2.1){u.position.x=lerp(u.position.x,road.point.x,1-Math.exp(-.8*dt));u.position.z=lerp(u.position.z,road.point.z,1-Math.exp(-.8*dt));u.position.y=expSmoothing(u.position.y,road.point.y+.055,14,dt)}else u.position.y=expSmoothing(u.position.y,terrainHeight(u.position.x,u.position.z)+.055,14,dt);u.mesh.position.copy(u.position);u.mesh.rotation.y=u.heading;const dist=u.position.distanceTo(player.position);if(dist<3.2&&u.cool<=0){if(player.ramArmed>.1){u.stun=.8+player.ramArmed*1.4;u.speed*=.45;u.cool=1.2;player.score+=Math.round(220+player.ramArmed*480);player.ramArmed*=.35;this.heat=clamp(this.heat+.03,0,1)}else{player.health=Math.max(0,player.health-(4+this.heat*9));player.speed*=.84;player.lastImpact=.55;u.cool=1;this.heat=clamp(this.heat+.035,0,1)}}}}
}
