import * as THREE from 'three';
import {clamp,lerp,expSmoothing,rad,fmtTime} from './core.js';

export class CameraRig{
  constructor(world,config){this.world=world;this.config=config;this.mode=0;this.shake=0;this.shakeSeed=0;this.fov=config.base_fov||64;this.look=new THREE.Vector3();this.pos=new THREE.Vector3()}
  cycle(){this.mode=(this.mode+1)%3}
  impact(v){this.shake=Math.max(this.shake,clamp(v,0,1))}
  update(dt,player,nitroMode=0,timeControl=false){const cam=this.world.camera,kmh=Math.abs(player.speed)*3.6,norm=clamp(kmh/400,0,1),fwd=new THREE.Vector3(Math.sin(player.heading),0,Math.cos(player.heading)),right=new THREE.Vector3(fwd.z,0,-fwd.x);let targetPos,targetLook;if(this.mode===2){targetPos=player.position.clone().add(new THREE.Vector3(0,1.15,0)).addScaledVector(fwd,.25);targetLook=player.position.clone().add(new THREE.Vector3(0,.9,0)).addScaledVector(fwd,22)}else if(this.mode===1){targetPos=player.position.clone().addScaledVector(fwd,-8.5-norm*2).add(new THREE.Vector3(0,4.7,0));targetLook=player.position.clone().add(new THREE.Vector3(0,.8,0)).addScaledVector(fwd,10)}else{targetPos=player.position.clone().addScaledVector(fwd,-11.5-norm*(this.config.speed_pullback||3.8)).add(new THREE.Vector3(0,5.1,0)).addScaledVector(right,-player.steer*.6);targetLook=player.position.clone().add(new THREE.Vector3(0,.75,0)).addScaledVector(fwd,(this.config.look_ahead||8.5)+norm*7)}this.pos.lerp(targetPos,1-Math.exp(-8*dt));this.look.lerp(targetLook,1-Math.exp(-9*dt));this.shake=Math.max(0,this.shake-dt*(this.config.shake_decay||7));if(this.shake>0){this.shakeSeed+=dt*53;this.pos.x+=Math.sin(this.shakeSeed*3.1)*this.shake*.18;this.pos.y+=Math.sin(this.shakeSeed*4.7)*this.shake*.12}cam.position.copy(this.pos);cam.lookAt(this.look);const targetFov=(this.config.base_fov||64)+norm*((this.config.max_fov||82)-(this.config.base_fov||64))+(nitroMode===3?5:nitroMode?2:0)-(timeControl?5:0);this.fov=expSmoothing(this.fov,targetFov,5,dt);cam.fov=this.fov;cam.updateProjectionMatrix()}
}

export class HUD{
  constructor(){this.root=document.querySelector('#raceHud');this.speed=document.querySelector('#speedText');this.lap=document.querySelector('#lapText');this.position=document.querySelector('#positionText');this.time=document.querySelector('#timeText');this.switch=document.querySelector('#switchText');this.health=document.querySelector('#healthBar');this.timeBar=document.querySelector('#timeBar');this.ramBar=document.querySelector('#ramBar');this.n1=document.querySelector('#n1');this.n2=document.querySelector('#n2');this.n3=document.querySelector('#n3');this.status=document.querySelector('#statusText');this.heat=document.querySelector('#heatBar');this.beat=document.querySelector('#beatText');this.rhythm=document.querySelector('#rhythmLanes');this.judge=document.querySelector('#rhythmJudge');this.minimap=document.querySelector('#minimap');this.mm=this.minimap?.getContext('2d')}
  show(v=true){this.root?.classList.toggle('active',v)}
  update(game){const p=game.player,s=p.currentStats(),r=game.race,n=game.nitro;this.speed.innerHTML=`${String(Math.round(Math.abs(p.speed)*3.6)).padStart(3,'0')} <small>km/h</small>`;this.lap.textContent=`VUELTA ${r.lap}/${r.laps}`;this.position.textContent=`${r.position}/${game.bots.length+1}`;this.time.textContent=fmtTime(r.time);this.switch.textContent=`${game.switch.a.name}  ${Math.round((1-game.switch.value)*100)}%  ↔  ${Math.round(game.switch.value*100)}%  ${game.switch.b.name}`;this.health.style.width=`${clamp(p.health/s.max_health*100,0,100)}%`;this.timeBar.style.width=`${p.timeReserve*100}%`;this.ramBar.style.width=`${p.ramCharge*100}%`;this.n1.style.width=`${n.n1*100}%`;this.n2.style.width=`${n.n2*100}%`;this.n3.style.width=`${n.n3*100}%`;if(this.heat)this.heat.style.width=`${game.pursuit.heat*100}%`;this.status.textContent=[game.beats.label,p.timeActive?'TIME CONTROL':'',p.ramArmed>.1?'RAM ARMED':'',n.mode===3?'TURBO NITRO':n.mode===2?'REMIX':n.mode===1?'NITRO':''].filter(Boolean).join(' · ');if(this.beat)this.beat.textContent=`${game.beats.label} · HEAT ${Math.round(game.pursuit.heat*5)}`;this.renderRhythm(game.rhythm);this.drawMinimap(game)}
  renderRhythm(r){if(!this.rhythm)return;this.rhythm.innerHTML='';for(const n of r.upcoming(9)){const el=document.createElement('i');el.className='note lane'+n.lane;el.style.bottom=`${clamp(12+n.delta*36,10,96)}%`;this.rhythm.append(el)}this.judge.textContent=r.judge}
  drawMinimap(game){if(!this.mm)return;const c=this.mm,w=c.canvas.width,h=c.canvas.height,pts=game.rt.points;c.clearRect(0,0,w,h);let minX=Infinity,maxX=-Infinity,minZ=Infinity,maxZ=-Infinity;for(const p of pts){minX=Math.min(minX,p.x);maxX=Math.max(maxX,p.x);minZ=Math.min(minZ,p.z);maxZ=Math.max(maxZ,p.z)}const s=Math.min((w-18)/(maxX-minX||1),(h-18)/(maxZ-minZ||1)),ox=(w-(maxX-minX)*s)/2,oy=(h-(maxZ-minZ)*s)/2;c.strokeStyle='rgba(210,235,245,.55)';c.lineWidth=3;c.beginPath();pts.forEach((p,i)=>{const x=ox+(p.x-minX)*s,y=oy+(p.z-minZ)*s;i?c.lineTo(x,y):c.moveTo(x,y)});c.closePath();c.stroke();const pp=pts[game.player.nearest];c.fillStyle='#21d5ff';c.beginPath();c.arc(ox+(pp.x-minX)*s,oy+(pp.z-minZ)*s,5,0,Math.PI*2);c.fill()}
}

export class ScreenManager{
  constructor(){this.screens=[...document.querySelectorAll('.screen')];this.history=['menu'];this.current='menu'}
  show(id,push=true){this.screens.forEach(s=>s.classList.toggle('active',s.id===id));if(push&&this.current!==id)this.history.push(id);this.current=id}
  back(){if(this.history.length>1)this.history.pop();this.show(this.history.at(-1)||'menu',false)}
  toast(text,ms=1600){const t=document.querySelector('#toast');if(!t)return;t.textContent=text;t.classList.add('show');clearTimeout(this._toast);this._toast=setTimeout(()=>t.classList.remove('show'),ms)}
}
